### ISSUE TITLE
all threads are WAITING when one master node is downing or starting

### ISSUE THREAD

**Issue by iamyuchen** [redis/jedis#1108]
redis version: 3.0.3
jedis version: 2.7.2/2.7.3

we have 64 nodes in the redis cluster, 32 masters, 32 slaves.
when one master is down, before the slave replace it,our program is dead.
all threads are waiting state, seems like deadlock?

jstack log is like this:

"Thread-2" prio=6 tid=0x05019c00 nid=0x28a4 waiting on condition [0x05b8f000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x297bda48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:583)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:98)
    at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:62)
    at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:115)
    at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
    at redis.clients.jedis.JedisCluster.get(JedisCluster.java:83)
    at outfox.dict.profile.service.CopyOfRedisService.getString(CopyOfRedisService.java:56)
    at outfox.dict.profile.service.MyThread.run(CopyOfRedisService.java:112)

   Locked ownable synchronizers:
    - None

"Thread-1" prio=6 tid=0x05019800 nid=0x2bb0 waiting on condition [0x05aff000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x297bda48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:583)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:98)
    at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:62)
    at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:115)
    at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
    at redis.clients.jedis.JedisCluster.get(JedisCluster.java:83)
    at outfox.dict.profile.service.CopyOfRedisService.getString(CopyOfRedisService.java:56)
    at outfox.dict.profile.service.MyThread.run(CopyOfRedisService.java:112)

   Locked ownable synchronizers:
    - None

**Comment by iamyuchen** [comment]
the above log is with jedis master

the last exception is:
redis.clients.jedis.exceptions.JedisDataException: LOADING Redis is loading the dataset in memory
	at redis.clients.jedis.Protocol.processError(Protocol.java:118)
	at redis.clients.jedis.Protocol.process(Protocol.java:152)
	at redis.clients.jedis.Protocol.read(Protocol.java:206)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:266)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:193)
	at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:116)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:41)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:113)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
	at redis.clients.jedis.JedisCluster.get(JedisCluster.java:83)

**Comment by ikozhuharov** [comment]
Same here with 3 masters and 3 slaves (everything works great till a master hiccups) : 
Attaching to process ID 7612, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.51-b03
Deadlock Detection:

No deadlocks found.

Thread 28785: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() @bci=42, line=2039 (Compiled frame)
 - org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst() @bci=20, line=583 (Interpreted frame)
 - org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(long) @bci=119, line=442 (Compiled frame)
 - org.apache.commons.pool2.impl.GenericObjectPool.borrowObject() @bci=5, line=363 (Compiled frame)
 - redis.clients.util.Pool.getResource() @bci=4, line=48 (Compiled frame)
 - redis.clients.jedis.JedisPool.getResource() @bci=1, line=86 (Compiled frame)
 - redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(int) @bci=14, line=57 (Compiled frame)
 - redis.clients.jedis.JedisClusterCommand.runWithRetries(java.lang.String, int, boolean, boolean) @bci=70, line=52 (Compiled frame)
 - redis.clients.jedis.JedisClusterCommand.run(java.lang.String) @bci=22, line=29 (Compiled frame)
 - redis.clients.jedis.JedisCluster.setex(java.lang.String, int, java.lang.String) @bci=20, line=251 (Compiled frame)

All (25) threads are blocked ...

**Comment by alessandro-modolo** [comment]
Hi all. We are facing the same problem. There is a workaround, or it will be scheduled to be fixed in the next version?

**Comment by sazzad16** [comment]
@alessandro-modolo Try setting a positive value in `setMaxWaitMillis` (or `setMaxWait`). Let us know if it works.

**Comment by sazzad16** [comment]
@alessandro-modolo thanks for giving the update
