### ISSUE TITLE
setTimeoutInfinite() in eval()

### ISSUE THREAD

**Issue by panchenko** [redis/jedis#1147]
At the moment eval is implemented like this

``` java
  public Object eval(String script, int keyCount, String... params) {
    client.setTimeoutInfinite();
    try {
      client.eval(script, keyCount, params);
      return getEvalResult();
    } finally {
      client.rollbackTimeout();
    }
  }
```

I am not sure if there are cases when eval execution takes a long time, one of our use cases is "distributed locks" as described in http://redis.io/topics/distlock and eval-ed script is pretty simple

``` lua
if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("del",KEYS[1])
else
    return 0
end
```

Unfortunately sometimes it hangs because of network issues.

In our case definitely continue with a default timeout should be OK.
If someone is doing a lot of computations in redis it would probably make sense to set some different timeout, but running without timeout could result is some vary long waits in case of network failures.

Thoughts?

**Comment by marcosnils** [comment]
@panchenko I have a question. What happens if when you get these network issues you send a `SCRIPT KILL` to redis. Does the application continue processing?

The reason why I'm asking this is because I've checked other clients (including the redis-cli code) and I've seen that none of them actually sets a timeout for the `eval` command. In addition do that, the Redis official docs state the following:

>SCRIPT KILL
This command is the only way to interrupt a long-running script that reaches the configured maximum execution time for scripts. The SCRIPT KILL command can only be used with scripts that did not modify the dataset during their execution (since stopping a read-only script does not violate the scripting engine's guaranteed atomicity). See the next sections for more information about long running scripts.

So I'm wondering if this is really necessary.

**Comment by panchenko** [comment]
I filed this after I've got alerts from tomcat on some stuck threads (i.e. requests taking >5 minutes) with the stack trace like the following:

```
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:152) 
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at java.net.SocketInputStream.read(SocketInputStream.java:108) 
at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195) 
at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) 
at redis.clients.jedis.Protocol.process(Protocol.java:132) 
at redis.clients.jedis.Protocol.read(Protocol.java:196) 
at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288) 
at redis.clients.jedis.Connection.getOne(Connection.java:270) 
at redis.clients.jedis.Jedis.getEvalResult(Jedis.java:2642) 
at redis.clients.jedis.Jedis.eval(Jedis.java:2582)
<our unlock method>
```

**Comment by marcosnils** [comment]
@panchenko do you have the lua-time-limit set?

**Comment by panchenko** [comment]
@marcosnils lua-time-limit has the default value of 5 seconds, I don't think it's related, as those few lines can't be slow and database is not that big.

**Comment by marcosnils** [comment]
@panchenko the thing is that we can't be sure that this fixes the issue as we can't reproduce it. When a connection is in this "hang" state, are you able to see it from the `client list` command in redis?

**Comment by panchenko** [comment]
I'll try some tests locally with 2 computers, at least that's feasible.

**Comment by marcosnils** [comment]
@panchenko wondering if you have any updates about this.

**Comment by sazzad16** [comment]
Closing this and #1148 due to inactivity.

**Comment by Huan9** [comment]
Not sure how to revive this thread, so I open a new issue link to this one: https://github.com/redis/jedis/issues/2270.

we also hit this issue and it is rarely repo but when it reproed, it cause serious issue. So we'd like to have some timeout in Lua script.

**Comment by sazzad16** [comment]
@Huan9 Jedis-3.4.0 has introduced a new `infiniteSoTimeout` parameter in constructors. Does it help?
