### ISSUE TITLE
when read time out, JedisCluster can not be retry

### ISSUE THREAD

**Issue by sd4324530** [redis/jedis#1812]
### Expected behavior

When read time out，keep data right always.

### Actual behavior

method:   JedisCluster.incrBy
when read time out, can not be retry!

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.JedisCluster cluster = new JedisCluster(new HostAndPort("xxx.xx.x.x", xxxx), 500, 100, 5, config);
2.cluster.incrBy(key, 5)
3.when read time out, the data will be go wrong

#### Jedis version:
2.9.0
#### Redis version:
3.0.7
#### Java version:
jdk1.8_45

**Comment by sd4324530** [comment]
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:151)
        at redis.clients.jedis.Protocol.read(Protocol.java:215)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
        at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
        at redis.clients.jedis.BinaryJedis.incrBy(BinaryJedis.java:732)
        at redis.clients.jedis.BinaryJedisCluster$23.execute(BinaryJedisCluster.java:296)
        at redis.clients.jedis.BinaryJedisCluster$23.execute(BinaryJedisCluster.java:293)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:120)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:60)
        at redis.clients.jedis.BinaryJedisCluster.incrBy(BinaryJedisCluster.java:298)

**Comment by sd4324530** [comment]
When the above error occurs, the framework will try again.

param maxAttempts > 1

**but it can not be retry**

if maxAttempts = 1 ,then when a cluster node has a problem, it will not be available

**Comment by Leeviiii** [comment]
I think jedis  can not guarantee the correctness of non-idempotent operations!

**Comment by sazzad16** [comment]
This is a very specific use case. It is highly unlikely to resolve unless there is a general purpose use case and/or no other way to solve.

To resolve the problem, either
- use `maxAttempts = 1`
- extend JedisCluster
- download/clone the project, edit code and use your own version.
