### ISSUE TITLE
if uri contains dbIndex, timeout configuration doesn't work 

### ISSUE THREAD

**Issue by jywjyw** [redis/jedis#1824]
### Expected behavior
set timeout to 10000 ms

### Actual behavior
timeout is 2000 ms as default

### Steps to reproduce:

1 .URI uri = new URI("redis://13.229.188.59:6379/1");//use fake address to test timeout
    Jedis jedis = new Jedis(uri, 10000);
2. when time passed 2 seconds, throws SocketTimeoutException, That's not my expected.
3. URI uri = new URI("redis://13.229.188.59:6379");//use fake address to test timeout
    Jedis jedis = new Jedis(uri, 10000);
    jedis.flushDB();
4. when time passed 10 seconds, throws SocketTimeoutException, That's expected.

**Comment by gkorland** [comment]
It seems like the bug is pretty obvious
```
  public BinaryJedis(final URI uri, final int connectionTimeout, final int soTimeout) {
    initializeClientFromURI(uri);
    client.setConnectionTimeout(connectionTimeout);
    client.setSoTimeout(soTimeout);
  }
```
As you can see the setConnectionTimeout is called after the call intializeClientFromURI, which in turn already open the client Socket.
```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host 13.229.188.59:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:98)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:125)
	at redis.clients.jedis.BinaryClient.select(BinaryClient.java:192)
	at redis.clients.jedis.BinaryJedis.initializeClientFromURI(BinaryJedis.java:171)
	at redis.clients.jedis.BinaryJedis.initializeClientFromURI(BinaryJedis.java:150)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:136)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:127)
	at redis.clients.jedis.Jedis.<init>(Jedis.java:106)
	at TestTimeout.main(TestTimeout.java:11)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
-->	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	... 9 more
```

And that is called since the DB index is 1>0

```
int dbIndex = JedisURIHelper.getDBIndex(uri);
    if (dbIndex > 0) {
      client.select(dbIndex);
      client.getStatusCodeReply();
      client.setDb(dbIndex);
    }
```
