### ISSUE TITLE
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by cholf** [redis/jedis#1970]
#### Sometimes occured error when we get;

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pss.jedis.JedisHandler.lambda$proxyJedis$2(JedisHandler.java:135)
	at redis.clients.jedis.Jedis$$EnhancerByCGLIB$$d8b7c579.mget(<generated>)

Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269)
	at redis.clients.jedis.Jedis.mget(Jedis.java:407)
	... 41 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)

### Actual behavior

sometimes occured error when we get;

### Steps to reproduce:

sometimes occured error when we get;

### Redis / Jedis Configuration
!!com.jedis.JedisYamlBean {
  jedisPoolBean: !!com.jedis.JedisPoolBean {
    maxTotal: 50000,
    maxIdle: 5000,
    maxWaitMillis: 3000,
    testOnBorrow: false,
    testOnReturn: false,
    blockWhenExhausted: false,
    numTestsPerEvictionRun: 100
  },
  jedisMasterNode: ${redis.master.nodes},
  jedisSlaveNode: ${redis.slave.nodes},
  timeout: 500,
  password: ${redis.password},
  maxAttempts: 2
}

#### Jedis version:
2.9.0
#### Redis version:
3.2
#### Java version:
1.8

**Comment by AndreGuima** [comment]
The same problem here =/

**Comment by sazzad16** [comment]
This seems like a network instability issue. There aren't much we can do from Jedis in such cases.

**Comment by otavio-zoop** [comment]
I had this problem on localhost, redis on docker

**Comment by otavio-zoop** [comment]
My test was a stress test, using redis to distributed lock, creating a lock an release, the problem occurred abouy 3k requests, 47 req/sec

**Comment by hello-dake** [comment]
same problem..
