### ISSUE TITLE
java.net.SocketInputStream.socketRead0(Native Method)

### ISSUE THREAD

**Issue by ravindrabhatt97** [redis/jedis#2046]
Hello Team,

I am getting below error stack trace, very intermittently in every 30 to 60 days, I get this stack trace for 10 to 30 mins(its the duration where user faces issue and we don't get any response back from redis) and then issues gets resolved on its own, can you please suggest something

Redis verison: 3.2.7
Jedis version: 2.9.0

["java.net.SocketInputStream.socketRead0(Native Method)", "java.net.SocketInputStream.socketRead(SocketInputStream.java:116)", "java.net.SocketInputStream.read(SocketInputStream.java:170)", "java.net.SocketInputStream.read(SocketInputStream.java:141)", "sun.security.ssl.InputRecord.readFully(InputRecord.java:465)", "sun.security.ssl.InputRecord.read(InputRecord.java:503)", "sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)", "sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)", "sun.security.ssl.AppInputStream.read(AppInputStream.java:105)", "java.io.InputStream.read(InputStream.java:101)", "redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)", "redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)", "redis.clients.jedis.Protocol.process(Protocol.java:151)", "redis.clients.jedis.Protocol.read(Protocol.java:215)", "redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)", "redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:259)", "redis.clients.jedis.Connection.getBulkReply(Connection.java:248)", "redis.clients.jedis.Jedis.get(Jedis.java:153)"

**Comment by zwqlive** [comment]
I have the similar problem
when I change the System Time, the Thread will be blocked
below is the stack trace
```
 java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:153)
	at redis.clients.jedis.Protocol.read(Protocol.java:218)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:341)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:266)
	at redis.clients.jedis.Jedis.exists(Jedis.java:214)
	at epoch.script.crosspk.CrosspkServScript.lambda$7(CrosspkServScript.java:575)
	at epoch.script.crosspk.CrosspkServScript$$Lambda$363/806151538.apply(Unknown Source)
	at epoch.game.core.function.FuncUtil.apply(Unknown Source)
	at epoch.game.core.actor.Actor.a(Unknown Source)
	at epoch.game.core.actor.Actor.a(Unknown Source)
	at epoch.game.core.actor.Actor.a(Unknown Source)
	at epoch.game.core.actor.ASystem$d.run(Unknown Source)

   Locked ownable synchronizers:
	- None
```
my code like this:
```
Jedis jedis = RedisManager.getGameJedis();
				try {
					HashMap<Integer, CrossGroupServerRegion> groups = param.get("groups");
					for (CrossGroupServerRegion crossGroupServerRegion : groups.values()) {
						int group = crossGroupServerRegion.getGroup();
						String redisCrosspkSortKey = getRedisCrosspkSortKey(group);
						String redisCrosspkServerKey = getRedisCrosspkServerKey(group);
						if (jedis != null && jedis.exists(redisCrosspkSortKey)) {
							jedis.del(redisCrosspkSortKey);
						}
						if (jedis != null && jedis.exists(redisCrosspkServerKey)) {
							jedis.del(redisCrosspkServerKey);
						}
						String servRegion = crossGroupServerRegion.getRegion();
						if (servRegion.length() > 0) {
							String[] servers = servRegion.split(Symbol.DOUHAO);
							for (String serverConf : servers) {
								if (serverConf.indexOf(Symbol.DUANHENGGAN) > 0) {
									String[] serverFromTo = serverConf.split(Symbol.DUANHENGGAN);
									int startId = Integer.parseInt(serverFromTo[0]);
									int endId = Integer.parseInt(serverFromTo[1]);
									for (int i = startId; i <= endId; i++) {
										String redisCrosspkServerPlayerIdKey = getRedisCrosspkServerPlayerIdKey(group, i);
										if (jedis != null && jedis.exists(redisCrosspkServerPlayerIdKey)) {
											jedis.del(redisCrosspkServerPlayerIdKey);
										}
									}
								} else {
									String redisCrosspkServerPlayerIdKey = getRedisCrosspkServerPlayerIdKey(group, Integer.parseInt(serverConf));
									if (jedis != null && jedis.exists(redisCrosspkServerPlayerIdKey)) {
										jedis.del(redisCrosspkServerPlayerIdKey);
									}
								}
							}
						}
					}
				} catch (Exception e) {
					Log.error("ERROR:", e);
				} finally {
					jedis.close();
				}
```
