### ISSUE TITLE
JedisConnectionException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by 6westboy9** [redis/jedis#2082]
### Expected behavior

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:153)
	at redis.clients.jedis.Protocol.read(Protocol.java:218)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:341)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:240)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:104)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:117)
	at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:560)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2222)
	at com.westboy.redis.test.JedisTest.main(JedisTest.java:28)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
	... 11 more
```

### Actual behavior

wang

Write here what happens instead ...

### Steps to reproduce:

```shell
# redis-cli -h 192.168.199.X -p 6379 -a xxx
192.168.199.180:6379> get name
"wang"
```
success !!!

```java
RedisURI redisURI =	RedisURI.Builder.redis("192.168.199.180", 6379).withPassword("tanwu_redis").build();
RedisClient client = RedisClient.create(redisURI);
StatefulRedisConnection<String, String> connection = client.connect();
RedisAsyncCommands<String, String> commands = connection.async();
RedisFuture<String> future = commands.get("name");
System.out.println(future.get()); // wang
```
success !!!

but...............

```java
Jedis jedis = new Jedis("192.168.199.X", 6379);
System.out.println(jedis);
jedis.auth("xxx");
System.out.println(jedis.ping());
```
```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:153)
	at redis.clients.jedis.Protocol.read(Protocol.java:218)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:341)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:240)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:104)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:117)
	at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:560)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2222)
	at com.westboy.redis.test.JedisTest.main(JedisTest.java:28)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
	... 11 more
```

### Redis / Jedis Configuration

```
```

#### Jedis version:

2.9.3

#### Redis version:

redis_version:3.2.11

#### Java version:

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by Force-King** [comment]
我也遇到这个问题了，最近线上 偶尔报这个错

**Comment by startjava** [comment]
你用DOCKER了吧？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CleverApe"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午2:16
收件人: "xetorthio/jedis"<jedis@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [xetorthio/jedis] JedisConnectionException: java.net.SocketTimeoutException: Read timed out (#2082)




我也遇到这个问题了，最近线上 偶尔报这个错
