### ISSUE TITLE
Getting JedisConnectionException in one particular operation

### ISSUE THREAD

**Issue by chanfool21** [redis/jedis#2187]
### Expected behavior

Write here what you're expecting ...
keys of a specific pattern should be filtered out and deleted from from redis server locally and in remote server as well  

### Actual behavior

Keys are getting deleted in local properly but while executing the jedis.keys() on remote server it is throwing following exception:

redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
    at redis.clients.jedis.Protocol.process(Protocol.java:153)
    at redis.clients.jedis.Protocol.read(Protocol.java:218)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:341)
    at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:277)
    at redis.clients.jedis.Jedis.keys(Jedis.java:284)

#### Java version: 1.8

Stackoverflow link: https://stackoverflow.com/questions/61285592/getting-jedisconnectionexception-in-one-particular-operation

**Comment by sazzad16** [comment]
@chanfool21 There can be too many keys in your Redis instance. So it could be taking too much time to read all of those and send them back over the network and the whole process could not finish within socket timeout.
