### ISSUE TITLE
Cannot initialize poolconfig

### ISSUE THREAD

**Issue by DevJoey** [redis/jedis#2188]
### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Make a plugin with maven and the newest Redis version

#### Jedis version:
Newest
#### Redis version:
Newest
#### Java version:
1.8.0

I use Redis in my Minecraft Plugin but if i enable it it dont work. On my localhost PC all works fine but on my Producktive Debian Server i got this unfixable error with no help and no fixes.

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/proxysocke/citybuildsystem/redis/RedisManager.connect()V @25: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[3]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @25
    flags: { }
    locals: { 'net/proxysocke/citybuildsystem/redis/RedisManager' }
    stack: { 'net/proxysocke/citybuildsystem/redis/RedisManager', uninitialized 1, uninitialized 1, 'redis/clients/jedis/JedisPoolConfig', 'java/lang/String', integer, integer, 'java/lang/String' }
  Bytecode:
    0x0000000: 2abb 0022 59bb 0024 59b7 0026 2ab4 0013
    0x0000010: 2ab4 0015 032a b400 19b7 0027 b500 2a2a
    0x0000020: b400 2ab6 002c 4c2b b600 30b2 0035 123b
    0x0000030: b600 3da7 0010 4cb2 0035 1243 b600 3d2b
    0x0000040: b600 45b1                              
  Exception Handler Table:
    bci [31, 51] => handler: 54
  Stackmap Table:
    same_locals_1_stack_item_frame(@54,Object[#70])
    same_frame(@67)

	at net.proxysocke.citybuildsystem.CityBuildSystem.setUpRedis(CityBuildSystem.java:139) ~[?:?]
	at net.proxysocke.citybuildsystem.CityBuildSystem.onEnable(CityBuildSystem.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[20:41:09] [Server thread/INFO]: [CityBuildSystem] Disabling CityBuildSystem v1.18.9-1.15
[20:41:09] [Server thread/ERROR]: Error occurred while disabling CityBuildSystem v1.18.9-1.15 (Is it up to date?)
java.lang.NullPointerException: null
	at net.proxysocke.citybuildsystem.CityBuildSystem.onDisable(CityBuildSystem.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by dengliming** [comment]
Can you please provide a code sample for the reproduction?
