### ISSUE TITLE
Cannot use Jedis when in Pipeline. Please use Pipeline or reset jedis state .

### ISSUE THREAD

**Issue by forachange** [redis/jedis#2199]
In the project, we used both the pipeline and the regular commands of jedis. 
However, in the project, when calling the regular command of jedis (not using pipeline or transaction), the following abnormal phenomena occur from time to time:

```
public String hget(String key, String field) {
	try (Jedis jedis = jedisResourcePool.getResource()) {
		return jedis.hget(key, field);
	}
}


public void hset(String key, String field, String value) {
	try (Jedis jedis = jedisResourcePool.getResource()) {
		jedis.hset(key, field, value);
	}
}
```

redis.clients.jedis.exceptions.JedisDataException: Cannot use Jedis when in Pipeline. Please use Pipeline or reset jedis state .
	at redis.clients.jedis.BinaryJedis.checkIsInMultiOrPipeline(BinaryJedis.java:1901)
	at redis.clients.jedis.Jedis.hset(Jedis.java:735)
	at com.bigdata.common.redis.CacheDataService.hset(CacheDataService.java:108)
	at com.bigdata.point.DataServiceImpl.saveRealPointValues(DataServiceImpl.java:218)
	at com.bigdata.point.DataServiceImpl$$FastClassBySpringCGLIB$$69e7e10a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.bigdata.point.DataServiceImpl$$EnhancerBySpringCGLIB$$ae4433a7.saveRealPointValues(<generated>)
	

redis.clients.jedis.exceptions.JedisDataException: Cannot use Jedis when in Pipeline. Please use Pipeline or reset jedis state .
	at redis.clients.jedis.BinaryJedis.checkIsInMultiOrPipeline(BinaryJedis.java:1838)
	at redis.clients.jedis.Jedis.hget(Jedis.java:676)
	at com.bigdata.common.redis.CacheDataService.hget(CacheDataService.java:118)
	at com.bigdata.point.DataServiceImpl.getRealPointValue(DataServiceImpl.java:268)
	at com.bigdata.point.DataServiceImpl.saveRealPointValues(DataServiceImpl.java:204)
	at com.bigdata.point.DataServiceImpl$$FastClassBySpringCGLIB$$69e7e10a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.bigdata.point.DataServiceImpl$$EnhancerBySpringCGLIB$$e468846.saveRealPointValues(<generated>)

**Comment by sazzad16** [comment]
@forachange It is not possible to use (and you shouldn't use) a Jedis object while it is being used in Pipeline. You can reuse it after Pipeline is done. In the mean time, you should use another Jedis.
