### ISSUE TITLE
Intermittent connection issue with Redis Sentinel

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2271]
My springboot application is running fine for hours. but time to time , I see connection lost exception to sentinel.

There is no network issue.

### Expected behavior

Write here what you're expecting ...

### Actual behavior

Intermittently, connection is getting lost from springboot app to sentinel

2020-10-30 20:59:34.742 [MasterListener-mymaster-[IP:26379]] [ERROR]:  redis.clients.jedis.JedisSentinelPool         - Lost connection to Sentinel at IP:26379. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:151)
        at redis.clients.jedis.Protocol.read(Protocol.java:215)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
        at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
        at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:121)
        at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:115)
        at redis.clients.jedis.Jedis.subscribe(Jedis.java:2680)
        at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:127)
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
        ... 9 common frames omitted

#### Jedis version:
Jedis 2.9

#### Redis version:
Redis 5.0
#### Java version:

JDK 8

Please help.

thanks

Jay

**Comment by steam0** [comment]
We see exactly the same behaviour in some of our applications. Has there not been any response to this at all?

**Comment by xiaoyaozi5566** [comment]
I observed the same behavior. I think the reason was that the idle connection was terminated by the server but the Java application doesn't clean up idle connection. So it kept using the expired connection, which resulted in this error. I've tried the solution in https://programmerah.com/solve-the-unexpected-end-of-stream-exception-thrown-by-jedis-536/, but didn't solve the problem. Please help!

**Comment by NK-debug** [comment]
Still happening, 4/2025. Redis 5.0.3

**Comment by ggivo** [comment]
From the initial comments, it sounds like this issue is tricky to reproduce and can take hours to manifest.
To properly investigate, we should first try to isolate the exact steps needed to reproduce it — ideally in a way that triggers it within a reasonable timeframe.

@NK-debug — have you been able to narrow down a reliable set of steps to reproduce the issue?
It would be especially helpful if you could include:

- The server configuration (especially any connection idle timeout settings)
- How the Jedis client is configured and used on your side
- A minimal code example, if possible

This would go a long way in helping us understand and address the problem. Thanks!

⸻

**Comment by NK-debug** [comment]
@ggivo here's some Java code to show the timeout issue. (Run with 1 parameter: 360)

`import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisSentinelPool;
// import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

import java.util.HashSet;
import java.util.Set;

/**
 * This RedisSentinelExample program will add a key/value to redis, and display the value on the console, hopefully before a Sentinel timeout occurs.<br>
 *
 * @author nk-debug
 * @version 1.0
 * @since 2024-03-28
 * <p>
 * v1.0, nk-debug, 2025-03-28 - Initial.<br>
 * v1.1, nk-debug, 2025-04-01 - try timeout from client.<br>
 */
public class RedisSentinelExample {
    public static void main(String[] args) throws InterruptedException {

        // Usage:
        // java RedisSentinelExample [sleep time in seconds]

        // To compile:
        // javac -cp .;jedis-5.2.0.jar;commons-pool2-2.12.1.jar;slf4j-simple-2.0.17.jar;slf4j-api-2.0.17.jar RedisSentinelExample.java
        // To run:
        // java -cp .;jedis-5.2.0.jar;commons-pool2-2.12.1.jar;slf4j-simple-2.0.17.jar;slf4j-api-2.0.17.jar RedisSentinelExample
		//   with a delay of 360 seconds (6 minutes):
        // java -cp .;jedis-5.2.0.jar;commons-pool2-2.12.1.jar;slf4j-simple-2.0.17.jar;slf4j-api-2.0.17.jar RedisSentinelExample 360

        // Define the Sentinel nodes
        Set<String> sentinels = new HashSet<>();
        sentinels.add("host1:26379");

        // Create a default Sentinel pool (with timeout of the redis sentinel server config?)
        JedisSentinelPool sentinelPool = new JedisSentinelPool("host1", sentinels);

		// Now try this:
        // Create a Sentinel pool with timeout set from client
		// JedisPoolConfig poolConfig = new JedisPoolConfig();
		// final int timeout=400; // sentinel timeout in seconds (seems to be ignored)
		// JedisSentinelPool sentinelPool = new JedisSentinelPool("host1", sentinels, poolConfig,timeout);

        // Get a Redis connection from the pool
        try (Jedis jedis = sentinelPool.getResource()) {
            // Perform Redis set operation
            System.out.println("Writing key/value...");
            jedis.set("ZZ99", "nk-debug was here");
			// Sleep, if necessary
			if (args.length==1) {
                System.out.println("Sleeping for "+args[0]+" seconds before retrieving key/value...");
                Thread.sleep((long)Integer.parseInt(args[0])*1000);
            }
            // Perform Redis get operation
            String value = jedis.get("ZZ99");
            System.out.println("Retrieved value: " + value);
		}

        // Close the pool
        sentinelPool.close();
    }
}`

**Comment by ggivo** [comment]
@NK-debug 
Thanks for the reproduction example. I did run it in my env but it seems to complete successfully without errors.

Jedis : 5.2.0
Redis : 8.0

```
[main] INFO redis.clients.jedis.JedisSentinelPool - Trying to find master from available Sentinels...
[main] INFO redis.clients.jedis.JedisSentinelPool - Redis master running at 127.0.0.1:6379, starting Sentinel listeners...
[main] INFO redis.clients.jedis.JedisSentinelPool - Created JedisSentinelPool to master at 127.0.0.1:6379
Writing key/value...
Sleeping for 360 seconds before retrieving key/value...
Retrieved value: nk-debug was here
```

**Comment by NK-debug** [comment]
So your Redis 8.0 default timeout is more than 300 seconds.
In Redis 5.0.3 I think it is 300.
Do you know what parameter/config value in what server config file stores
that parameter in Redis 5? I can pass that along to our Redis admin.

You can also try larger values than 360 to see if/when the "Lost connection
to Sentinel" error occus in Redis 8.

**Comment by ggivo** [comment]
If I am reading the docs correctly [Client Timeouts](https://redis.io/docs/latest/develop/reference/clients/) it is configurable via
`CONFIG SET timeout` or directly through `redis.conf`

**Comment by ggivo** [comment]
@NK-debug 
From the provided example don't see an issue with the driver.
We get a connection from the pool, then wait till the server idle timeout is reached and a disconnect is initiated from the server side. When we later try to use the disconnected connection, it throws an error.

One way to address this is to return the connection to the pool, and get new one when needed.
