### ISSUE TITLE
ClassCastException error while using jediscluster

### ISSUE THREAD

**Issue by baitianxia** [redis/jedis#2316]
### Expected behavior
when I using jedisCluster like this in flink，I got error “java.lang.ClassCastException” 
```java
new RichSinkFunction<StreamingJob.Event>(){
    private JedisCluster jedisCluster;
    public void open (Configuration parameters) throws Exception {
         //my nodes config
         this.jedisCluster = new JedisCluster(nodes);
    }
    @Override
    public void invoke (StreamingJob.Event event, SinkFunction.Context context) throws Exception {
          List<String> buckets = jedisCluster.lrange("key", 0, 0);
          if (buckets == null || buckets.size() == 0) {
               //do something
               jedisCluster.rpush("key", "value");
          } else {
              //do something
               jedisCluster.lset("key", 0, "value");
          }
     }
}
```
Write here what you're expecting ...

### Actual behavior
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Long
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:220)
	at redis.clients.jedis.Jedis.rpush(Jedis.java:964)
	at redis.clients.jedis.JedisCluster$47.execute(JedisCluster.java:638)
	at redis.clients.jedis.JedisCluster$47.execute(JedisCluster.java:635)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:106)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:25)
	at redis.clients.jedis.JedisCluster.rpush(JedisCluster.java:640)
Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Jedis version:
3.3.0
#### Java version:
1.8

**Comment by baitianxia** [comment]
sorry，it's an error on my server，not jedis
