### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR command is not allowed

### ISSUE THREAD

**Issue by bhawani021** [redis/jedis#2317]
### 

There should be a connection for Java app to Redis DB

### Actual behavior

Geeting error -> redis.clients.jedis.exceptions.JedisDataException: ERR command is not allowed

### Steps to reproduce:

```
 redis.clients.jedis.JedisCluster cmd = new redis.clients.jedis.JedisCluster(
                new HostAndPort("myhost", 12075),
                1000,
                1000,
                3,
                "<PASSWORD>",
                genericObjectPoolConfig);
```

```
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR command is not allowed
	at redis.clients.jedis.Protocol.processError(Protocol.java:132) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:166) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3435) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:73) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:61) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:33) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:24) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:19) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:27) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:60) ~[jedis-3.1.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:114) ~[jedis-3.1.0.jar!/:?]
	at com.netflix.conductor.redis.config.RedisClusterConfiguration.createJedisCommands(RedisClusterConfiguration.java:90) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.redis.config.JedisCommandsConfigurer.jedisCommands(JedisCommandsConfigurer.java:23) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
	at com.netflix.conductor.redis.config.RedisClusterConfiguration.jedisCommands(RedisClusterConfiguration.java:30) ~[conductor-redis-persistence-0.1.0-dev.0.uncommitted.jar!/:0.1.0-dev.0.uncommitted]
```

**Comment by sazzad16** [comment]
@bhawani021 `CLUSTER SLOTS` command is disabled in your Redis instances. But Jedis internally uses that command to get cluster configuration. Please check the configuration of your Redis instances.

**Comment by sazzad16** [comment]
Closed due to inactivity.
