### ISSUE TITLE
NoSuchMethodError with Jedis 3.4.1 on Java 8

### ISSUE THREAD

**Issue by YNedderhoff** [redis/jedis#2337]
I started to see these errors after upgrading a Java 8 (complied and run) application from Jedis 3.3.0 to 3.4.1. Googling the issue yields several sources that say it might be related to `Buffer` and `ByteBuffer` when switching from Java 8 to 11, but I haven't verified that ([Stackoverflow](https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip)).

Is it maybe possible Jedis was compiled with JDK 8 before, but is now on a higher version?

### Expected behavior

No error when getting a resource from a `ShardedJedisPool`

### Actual behavior

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at redis.clients.jedis.util.MurmurHash.hash64A(MurmurHash.java:126)
	at redis.clients.jedis.util.MurmurHash.hash64A(MurmurHash.java:94)
	at redis.clients.jedis.util.MurmurHash.hash(MurmurHash.java:141)
	at redis.clients.jedis.util.MurmurHash.hash(MurmurHash.java:146)
	at redis.clients.jedis.util.Sharded.initialize(Sharded.java:58)
	at redis.clients.jedis.util.Sharded.<init>(Sharded.java:48)
	at redis.clients.jedis.BinaryShardedJedis.<init>(BinaryShardedJedis.java:37)
	at redis.clients.jedis.ShardedJedis.<init>(ShardedJedis.java:36)
	at redis.clients.jedis.ShardedJedisPool$ShardedJedisFactory.makeObject(ShardedJedisPool.java:72)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:918)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:431)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:356)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.ShardedJedisPool.getResource(ShardedJedisPool.java:36)
```

**Comment by gkorland** [comment]
@YNedderhoff can you please try with the following? 
https://oss.sonatype.org/content/repositories/snapshots/redis/clients/jedis/3.5.1-SNAPSHOT/jedis-3.5.1-20210121.201726-1.jar

**Comment by sazzad16** [comment]
@gkorland that jar as well as the maven snapshot of 3.5.1 is working in my testing.

**Comment by YNedderhoff** [comment]
It would be much easier if I could test with a maven dependency - How can I use the maven snapshot?

**Comment by sazzad16** [comment]
@YNedderhoff Check https://github.com/redis/jedis#snapshots 
The `repositories` is at the same level of the `dependencies`. And put `3.5.1-SNAPSHOT` as version.

**Comment by YNedderhoff** [comment]
@gkorland I just gave this a spin, my issue seems to be fixed 🙂 Thanks!

**Comment by sazzad16** [comment]
@YNedderhoff Jedis 3.5.1 is released officially. Thank you for your contribution.

**Comment by YNedderhoff** [comment]
Thanks for the quick fix!
