### ISSUE TITLE
Could not get a resource from the pool (JedisConnectionException)

### ISSUE THREAD

**Issue by seqwait** [redis/jedis#2432]
1. jedis(2.9.0)
2. the problem ! exception (every day once) 

```
09:30:17.311 [MQTT Call: ms-java-mqtt-server@paho11476883539829881] ERROR c.ll.message.web.common.Executor - numIdle=>0,numActive=>1000
09:30:17.312 [MQTT Call: ms-java-mqtt-server@paho11476883539829881] INFO  c.ll.message.web.common.Executor - Could not get a resource from the pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at com.ll.message.web.common.Executor.<init>(Executor.java:22)
	at com.ll.message.web.common.CacheManager$12.<init>(CacheManager.java:222)
	at com.ll.message.web.common.CacheManager.hset(CacheManager.java:222)
	at com.ll.message.core.manager.MessageManager.online(MessageManager.java:113)
	at com.ll.message.core.manager.listeners.ClientConnectedListener.messageArrived(ClientConnectedListener.java:39)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:511)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:594)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:437)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 16 common frames omitted
```
3. java stack

```
"DubboServerHandler-172.17.110.200:30002-thread-77" #377 daemon prio=5 os_prio=0 tid=0x00007ff4bc07e800 nid=0x7806 waiting on condition [0x00007ff48fe6d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c6366800> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:594)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:437)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at com.ll.message.web.common.Executor.<init>(Executor.java:22)
	at com.ll.message.web.common.CacheManager$11.<init>(CacheManager.java:203)
	at com.ll.message.web.common.CacheManager.hgetAll(CacheManager.java:203)
	at com.ll.message.web.user.UserService.getBaseByUid(UserService.java:66)
	at com.ll.message.push.PushService.push(PushService.java:31)
	at com.ll.message.core.api.DefaultMessageService.push(DefaultMessageService.java:79)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)
	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:73)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:138)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:104)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:173)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
4. jedis exec core code

```
    Jedis jedis;
    JedisPool jedisPool;

    public Executor(JedisPool jedisPool, int dbIndex) {
        try {
            this.jedisPool = jedisPool;
            jedis = this.jedisPool.getResource();
            jedis.select(dbIndex);
            log.info("idle=>{},active=>{}", jedisPool.getNumIdle(), jedisPool.getNumActive());
        } catch (Exception e) {
            log.error("numIdle=>{},numActive=>{}", jedisPool.getNumIdle(), jedisPool.getNumActive());
            log.info(e.getMessage(), e);
            if (jedis != null) {
                try {
                    jedis.close();
                } catch (Exception ex) {
                    log.error("jedis-close-error", ex);
                } finally {
                    jedis.close();
                }
            }
        }
    }

    abstract T execute();

    public T getResult() {
        T result = null;
        try {
            result = execute();
        } catch (Throwable e) {
            if (jedis != null)
                jedis.close();
            log.error("numIdle=>{},numActive=>{}", jedisPool.getNumIdle(), jedisPool.getNumActive());
            throw new RuntimeException("Redis execute exception ", e);
        } finally {
            try {
                if (jedis != null)
                    jedis.close();
            } catch (Exception ex) {
                log.error("jedis-close-error", ex);
            }
        }
        return result;
    }
```

**Comment by sazzad16** [comment]
@seqwait Did you try a newer/updated version?

**Comment by seqwait** [comment]
ok , i will .

**Comment by seqwait** [comment]
> @seqwait Did you try a newer/updated version?

thanks , i will try!

**Comment by seqwait** [comment]
> @seqwait Did you try a newer/updated version?

the issue still!

**Comment by dengliming** [comment]
If it was occasional, you can try to increase the `maxTotal ` of `JedisPoolConfig`. The default value is `8`. If still not working, you also need to check if there are some slow query occupants.

**Comment by sazzad16** [comment]
You can also try setting a positive number in `setMaxWaitMillis()`.

**Comment by seqwait** [comment]
> setMaxWaitMillis

the config
    JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxIdle(100);
        jedisPoolConfig.setMaxTotal(3000);
        jedisPoolConfig.setMinIdle(100);
        jedisPoolConfig.setMaxWaitMillis(1000);
        jedisPoolConfig.setJmxEnabled(true);
        JedisPool jedisPool = new JedisPool(jedisPoolConfig, this.hostName, this.port, 10000, this.password);
        return jedisPool;

today log still increase !
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
mon.Executor - idle=>
mon.Executor - idle=>
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
mon.Executor - idle=>

**Comment by seqwait** [comment]
> You can also try setting a positive number in `setMaxWaitMillis()`.

the config
    JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxIdle(100);
        jedisPoolConfig.setMaxTotal(3000);
        jedisPoolConfig.setMinIdle(100);
        jedisPoolConfig.setMaxWaitMillis(1000);
        jedisPoolConfig.setJmxEnabled(true);
        JedisPool jedisPool = new JedisPool(jedisPoolConfig, this.hostName, this.port, 10000, this.password);
        return jedisPool;

today log still increase !
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
mon.Executor - idle=>
mon.Executor - idle=>
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
idle=>96,active=>907,
mon.Executor - idle=>
mon.Executor - idle=>

**Comment by sazzad16** [comment]
Try latest version of commons-pool2.

**Comment by sazzad16** [comment]
```
            jedis = this.jedisPool.getResource();
```

Is `jedis` a shared variable? You should not use Jedis objects from multiple threads. Using same reference from multiple methods increases the chance of objects to be used from multiple threads at the same time.

**Comment by seqwait** [comment]
> ```
>             jedis = this.jedisPool.getResource();
> ```
> 
> Is `jedis` a shared variable? You should not use Jedis objects from multiple threads. Using same reference from multiple methods increases the chance of objects to be used from multiple threads at the same time.

not a shared variable ?   i will new Executor .

abstract class Executor<T> {
    Executor();
   abstract T execute();
   getResult();
}

 public long incrBy(String key, int dbIndex, int integer) {
        return new Executor<Long>(jedisPool, dbIndex) {
            @Override
            Long execute() {
                Long rs = jedis.incrBy(key, integer);
                return Optional.ofNullable(rs).orElse(0l);
            }
        }.getResult();
    }

**Comment by seqwait** [comment]
mbean

```
 AbandonedConfig                   false
 BlockWhenExhausted                true
 BorrowedCount                     118999
 Closed                            false
 CreatedCount                      2666
 CreationStackTrace                java.lang.Exception
 DestroyedByBorrowValidationCount  0
 DestroyedByEvictorCount           2478
 DestroyedCount                    2480
 FactoryType                       redis.clients.jedis.JedisFactory<redis.clients.jedis.Jedis>
 Fairness                          false
 Lifo                              true
 LogAbandoned                      false
 MaxBorrowWaitTimeMillis           48
 MaxIdle                           100
 MaxTotal                          3000
 MaxWaitMillis                     1000
 MeanActiveTimeMillis              1
 MeanBorrowWaitTimeMillis          0
 MeanIdleTimeMillis                288
 MinEvictableIdleTimeMillis        60000
 MinIdle                           100
 NAME                              VALUE
 NumActive                         86
 NumIdle                           100
 NumTestsPerEvictionRun            -1
 NumWaiters                        0
 RemoveAbandonedOnBorrow           false
 RemoveAbandonedOnMaintenance      false
 RemoveAbandonedTimeout            2147483647
 ReturnedCount                     118913
 TestOnBorrow                      false
 TestOnCreate                      false
 TestOnReturn                      false
 TestWhileIdle                     true
 TimeBetweenEvictionRunsMillis     30000

**Comment by qingdengyue** [comment]
so what happened? any way to resolve ?
