### ISSUE TITLE
An java.lang.ClassCastException occurs while QUIT

### ISSUE THREAD

**Issue by dengliming** [redis/jedis#2479]
### Expected behavior

No Warn Exception

### Actual behavior
```

[WARN ] 2021-03-23T01:42:39,330 [main]         r.c.j.ShardedJedisPool - Error while QUIT java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:265) ~[classes/:?]
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:457) ~[classes/:?]
	at redis.clients.jedis.ShardedJedisPool$ShardedJedisFactory.destroyObject(ShardedJedisPool.java:84) [classes/:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:126) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:958) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:677) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:721) [commons-pool2-2.9.0.jar:2.9.0]
	at redis.clients.jedis.util.Pool.closeInternalPool(Pool.java:122) [classes/:?]
	at redis.clients.jedis.util.Pool.destroy(Pool.java:109) [classes/:?]
	at redis.clients.jedis.tests.ShardedJedisPoolTest.returnResourceShouldResetState(ShardedJedisPoolTest.java:235) [test-classes/:?]
	... suppressed 29 lines
```

see more detail [https://app.circleci.com/pipelines/github/redis/jedis/615/workflows/132a377c-6072-4ee9-9f5d-9d63e208dc9a/jobs/754](https://app.circleci.com/pipelines/github/redis/jedis/615/workflows/132a377c-6072-4ee9-9f5d-9d63e208dc9a/jobs/754)

**Comment by deepakguruu** [comment]
Getting this same issue when moving to Jedis 3.2
`java.lang.ClassCastException: [B cannot be cast to java.util.List
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Transaction.exec(Transaction.java:46)`
