### ISSUE TITLE
JedisFactory.destroyObject should not try to remove object from pool.

### ISSUE THREAD

**Issue by Anand-Tableau** [redis/jedis#2604]
Thanks to @sazzad16, he mentioned that JedisFactory.destroyObject should not be trying to return a resource to the pool. Else I would have had to go through commons-pool2 documentation to figure out if this was an issue with commons-pool or if this was an issue with Jedis. Please see more details in https://github.com/redis/jedis/discussions/2603#discussioncomment-1035222

### Expected behavior
JedisFactory.destroyObject should not attempt tor return the object to the pool via Jedis.close() as the pool itself may be calling JedisFactory.destroyObject after eviction.

### Actual behavior
Jedis destroyObject can be called from commons-pool2 eviction thread.
commons-pool2 has already returned the object and that leads to logging an exception. In our sandbox environment we are seeing around 70K exceptions thrown after upgrading from Jedis 2.9.0 to Jedis 3.6.0 causing lot of noise in the logs and will overwhelm our logging infrastructure(splunk) if we deploy this to production. Attaching a sample such log, it amounts to about 2300 characters and is causing ~160MB of noise daily in our sandbox environment.
<pre>
2021-07-16 18:03:57.354 -0700 (,,,) commons-pool-evictor-thread : WARN  wgsessionId= redis.clients.jedis.JedisFactory - Error while close
redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
	at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:116) ~[jedis-3.6.0.jar:?]
	at redis.clients.jedis.util.Pool.returnBrokenResource(Pool.java:98) ~[jedis-3.6.0.jar:?]
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:378) ~[jedis-3.6.0.jar:?]
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:15) ~[jedis-3.6.0.jar:?]
	at redis.clients.jedis.Jedis.close(Jedis.java:3957) ~[jedis-3.6.0.jar:?]
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:166) [jedis-3.6.0.jar:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:126) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:958) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:797) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1160) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:213) [commons-pool2-2.9.0.jar:2.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:642) ~[commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:620) ~[commons-pool2-2.9.0.jar:2.9.0]
	at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:114) ~[jedis-3.6.0.jar:?]
	... 16 more
</pre>
### Steps to reproduce:
I don't have a repro but I have callstacks with source code to illustrate the problem. Copying the same from the linked discussion:
Callstack1 from debugger shows JedisFactory looking to return the object to the pool.
Note the pool instance GenericObjectPool@24451 and it wants to fetch the object from allObjects variable on line 637.
![Callstack1-JedisIssue](https://user-images.githubusercontent.com/87782925/126572966-dc6eaf45-1fa6-4d00-a65e-ab4a3015728a.png)
 
Looking at what happened before in the callstack, here is the object pool calling the factory to destroy the object.
Notice that the object pool instance matches, but the pool already removed the object from allObjects variable on line 956.
JedisFactory.destroyObject is called by  commons-pool when evicting objects, and is called after evicting the object from the pool.
![Callstack2-JedisIssue](https://user-images.githubusercontent.com/87782925/126572932-dc73da5e-cbf0-4a05-b5d6-d78c8675d64b.png)

### Redis / Jedis Configuration
Not applicable

#### Jedis version:
3.6.0

#### Redis version:
6.0.11 (Not applicable)

#### Java version:
Java 11.

**Comment by Anand-Tableau** [comment]
This was not the issue as discussed in the linked thread
