### ISSUE TITLE
Could not return resource to pool : Redis cluster pipeline

### ISSUE THREAD

**Issue by YashKushwaha01** [redis/jedis#2623]
Redis version 3.0.0 snapshot is creating this issue
I'm frequently getting this exception after calling sync()

**Comment by sazzad16** [comment]
@YashKushwaha01 

---

About versions:

1. The snapshot version you provided, is it for Redis or Jedis?
2. Is the version 3.0.0 snapshot or 4.0.0 snapshot?

---

About cluster pipeline:

Jedis doesn't have (not even in snapshot) out of the box pipeline support in cluster mode.

Users can do pipelining per node, but it's at their own risk.

---

Finally:

The information given is really not enough to help. Please add the stacktrace, code snippet that's generating the exception, etc.

**Comment by YashKushwaha01** [comment]
Here is the stack trace - 
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:88)
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:235)
	at redis.clients.jedis.Jedis.close(Jedis.java:3447)
	at redis.clients.jedis.JedisClusterPipeline.releaseConnection(JedisClusterPipeline.java:278)
	at redis.clients.jedis.JedisClusterPipeline.reset(JedisClusterPipeline.java:288)
	at redis.clients.jedis.JedisClusterPipeline.sync(JedisClusterPipeline.java:314)
	at start.PutInRedis.run(PutInRedis.java:197)
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:640)
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:86)


Previously there was a branch for the cluster pipeline but now the branch has been removed.
I was getting a huge performance improvement using the same but when applied on production,It started throwing this error.

**Comment by sazzad16** [comment]
`JedisClusterPipeline` is not something that this official Jedis project has or ever had. Perhaps you're using a fork. Please consult with the respective repo. Thank you :)
