### ISSUE TITLE
Jedis 2.9.0  error：pool not open

### ISSUE THREAD

**Issue by zhyhzhylove** [redis/jedis#2637]
### Expected behavior

pool not open

### Actual behavior

Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.util.Pool.getResource(Pool.java:49)

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Jedis version:
2.9.0
#### Java version:

1.8

**Comment by yangbodong22011** [comment]
Have you ever called `pool.close()` in your code.

**Comment by zhyhzhylove** [comment]
> Have you ever called `pool.close()` in your code.

No，when the app started，this erro is reported，only occasionally。

**Comment by sazzad16** [comment]
@zhyhzhylove Are you using JedisSentinelPool?

**Comment by zhyhzhylove** [comment]
> @zhyhzhylove Are you using JedisSentinelPool?

NO。May can close this issue.Thanks.
