### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command `CONFIG`, with args beginning with: `get`, `databases`,  

### ISSUE THREAD

**Issue by gerryhjs** [redis/jedis#2647]
### Expected behavior

Connect to redis in docker.

### Actual behavior

Connect failed.

Error stack:
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command `CONFIG`, with args beginning with: `get`, `databases`, 
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:270)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:264)
	at redis.clients.jedis.Jedis.configGet(Jedis.java:2769)

**Comment by yangbodong22011** [comment]
@gerryhjs `unknown command` means redis does not support this command. but `CONFIG` command, redis support form `2.0.0` [version](https://redis.io/commands/config-get). so you may connect to a `proxy` or your endpoint does not support `CONFIG` command, please check it.
This has nothing to do with Jedis.
