### ISSUE TITLE
Jedis 3.2.0 error：No reachable node in cluster

### ISSUE THREAD

**Issue by HAND-jinliang** [redis/jedis#2665]
### Expected behavior

Successfully get AWS redis cluster connection.

### Actual behavior
An exception occurred when we were connecting to AWS redis cluster. The exceptions are as follows:

Caused by: redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: **No reachable node in cluster**
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:69)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:102)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:25)
	at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:593)

### Steps to reproduce:
When we perform redis query on a batch of data, an exception occurs in one of the data when obtaining redis connection. It is preliminarily judged that it is a bug of jedis

#### Jedis version:
jedis-3.2.0.jar
#### Redis version:
AWS Redis Cluster
#### Java version:
java version "1.8.0_112"

**Comment by sazzad16** [comment]
Closed due to inactivity.
