### ISSUE TITLE
JedisSentinelPool - Unexpected end of stream.

### ISSUE THREAD

**Issue by arpanpatel1992** [redis/jedis#2727]
Hello All, I am facing below issue on Redis 5.0.3 version using JedisSentinelPool client.

```
Fri Dec 10 11:56:41 EST 2021 WARN  [redis.clients.jedis.JedisFactory] (commons-pool-evictor-thread) Error while QUIT: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202) [jedis-3.7.0.jar:]
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) [jedis-3.7.0.jar:]
        at redis.clients.jedis.Protocol.process(Protocol.java:162) [jedis-3.7.0.jar:]
        at redis.clients.jedis.Protocol.read(Protocol.java:227) [jedis-3.7.0.jar:]
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) [jedis-3.7.0.jar:]
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270) [jedis-3.7.0.jar:]
        at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:471) [jedis-3.7.0.jar:]
        at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:160) [jedis-3.7.0.jar:]
        at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:126) [commons-pool2-2.9.0.jar:2.9.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:958) [commons-pool2-2.9.0.jar:2.9.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:797) [commons-pool2-2.9.0.jar:2.9.0]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1160) [commons-pool2-2.9.0.jar:2.9.0]
        at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:213) [commons-pool2-2.9.0.jar:2.9.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_232]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_232]
```
version:

Redis version 5.0.3
Jedis version 3.0.7
Java 8

Poolconfig properties:

```
GenericObjectPoolConfig<Jedis> jedisPoolConfig = new GenericObjectPoolConfig<>();
        jedisPoolConfig.setMaxTotal(50);        
        jedisPoolConfig.setMinIdle(1);
        jedisPoolConfig.setMaxIdle(5);        
        jedisPoolConfig.setTestOnBorrow(true);        
        jedisPoolConfig.setTestWhileIdle(true);
        jedisPoolConfig.setTestOnReturn(true);
```

Any suggestion would be appreciated.

**Comment by sazzad16** [comment]
@arpanpatel1992 There are no issues. Extra connections are just being cleaned up. You can consider increasing MaxIdle, which would hold more extra connections and reduce logging. Or, if you find those logging annoying, increase the level of logging over WARN, e.g. ERROR.

**Comment by arpanpatel1992** [comment]
@sazzad16 Thank you for the information. Also, I override setMinEvictableIdleTimeMillis property with higher value.
