### ISSUE TITLE
"Error while QUIT" seen in the logs some times

### ISSUE THREAD

**Issue by conghairui** [redis/jedis#2772]
### Expected behavior

If it does not affect the use, it does not output errors

### Actual behavior

```
2021-12-27 14:53:12.758  WARN 3040 --- [-evictor-thread] r.c.j.JedisFactory                       : Error while QUIT

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:158) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:223) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:472) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:160) [jedis-3.6.3.jar:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:126) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:958) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:797) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1160) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:213) [commons-pool2-2.9.0.jar:2.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:127) ~[?:1.8.0_171]
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:199) ~[jedis-3.6.3.jar:?]
	... 20 more
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.redis.clients.jedis.Connection#getStatusCodeReply, while sendCommand is Protocol.Command.QUIT
2.If the return value is read 1 second after flush 
3."Error while QUIT" will be seen

**Comment by yangbodong22011** [comment]
@conghairui Yes, this does not affect the use, because it occurs when the connection pool is expelled, perhaps Redis is no longer available at this time.

We will evaluate whether to control whether to print this type of log through an option, WDYT? @sazzad16

**Comment by sazzad16** [comment]
@yangbodong22011 User can control such logging. 

@conghairui Please look into your logging framework to limit these logs.

**Comment by conghairui** [comment]
> @yangbodong22011 User can control such logging.
> 
> @conghairui Please look into your logging framework to limit these logs.

ok. Thank You

**Comment by yangbodong22011** [comment]
> @yangbodong22011 User can control such logging.

@sazzad16 you mean set logLevel bigger than `warn`?

**Comment by sazzad16** [comment]
> @sazzad16 you mean set logLevel bigger than warn?

@yangbodong22011 Simply, yes. But modern logging frameworks can also ignore logs by pattern.

**Comment by yangbodong22011** [comment]
> > @sazzad16 you mean set logLevel bigger than warn?
> 
> @yangbodong22011 Simply, yes. But modern logging frameworks can also ignore logs by pattern.

OK, let us reach an agreement. If a similar issue occurs again, our suggestion is to avoid such logs through logging frameworks.

I think the reason why we do not add parameters to control whether to print such logs is that it is useful for users to troubleshoot problems, and we want it to print by default.

**Comment by sazzad16** [comment]
@yangbodong22011 agree :100:
