### ISSUE TITLE
Error while close or on eviction runs

### ISSUE THREAD

**Issue by andreasdc** [redis/jedis#2787]
### Expected behavior

Flawless working of Jedis without any errors.

### Actual behavior

Sometimes I get this error:
[07:17:12] [commons-pool-evictor/WARN]: [commons-pool-evictor] WARN redis.clients.jedis.JedisFactory - Error while close
[07:17:12] [commons-pool-evictor/WARN]: redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
[07:17:12] [commons-pool-evictor/WARN]: 	at redis.clients.jedis.util.Pool.returnBrokenResource(Pool.java:60)
[07:17:12] [commons-pool-evictor/WARN]: 	at redis.clients.jedis.Jedis.close(Jedis.java:283)
[07:17:12] [commons-pool-evictor/WARN]: 	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:170)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:127)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:611)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:729)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:160)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:113)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:17:12] [commons-pool-evictor/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:17:12] [commons-pool-evictor/WARN]: Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:936)
[07:17:12] [commons-pool-evictor/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:914)
[07:17:12] [commons-pool-evictor/WARN]: 	at redis.clients.jedis.util.Pool.returnBrokenResource(Pool.java:58)
[07:17:12] [commons-pool-evictor/WARN]: 	... 13 more

or this error when disabling:
[07:21:33] [Server thread/WARN]: [Server thread] WARN redis.clients.jedis.JedisFactory - Error while close
[07:21:33] [Server thread/WARN]: redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
[07:21:33] [Server thread/WARN]: 	at redis.clients.jedis.util.Pool.returnBrokenResource(Pool.java:60)
[07:21:33] [Server thread/WARN]: 	at redis.clients.jedis.Jedis.close(Jedis.java:283)
[07:21:33] [Server thread/WARN]: 	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:170)
[07:21:33] [Server thread/WARN]: 	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:127)
[07:21:33] [Server thread/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:611)
[07:21:33] [Server thread/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:461)
[07:21:33] [Server thread/WARN]: 	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:495)
[07:21:33] [Server thread/WARN]: 	at redis.clients.jedis.util.Pool.destroy(Pool.java:26)
### Steps to reproduce:

Wait for eviction run.
or
Stop the app.

**Comment by andreasdc** [comment]
"Error while close"?

**Comment by sazzad16** [comment]
"WARN"

**Comment by andreasdc** [comment]
> "WARN"

From what I think it can't destroy resource? How to avoid this unwanted behaviour?

**Comment by sazzad16** [comment]
> From what I think it can't destroy resource? How to avoid this unwanted behaviour?

@andreasdc The resource was destroyed. The log indicates that _something_ about the object was not ideal. There are way too many possible cases to list why this could happen. If you find the logs annoying, you can disable the logs. Consult your team member who manages the logging.

**Comment by andreasdc** [comment]
> > From what I think it can't destroy resource? How to avoid this unwanted behaviour?
> 
> @andreasdc The resource was destroyed. The log indicates that _something_ about the object was not ideal. There are way too many possible cases to list why this could happen. If you find the logs annoying, you can disable the logs. Consult your team member who manages the logging.

I'm managing this by myself, but this error/warning wasn't there all the time, it started to happen since some version, but I want to keep it perfect, so my guess it that I do something wrong or not ideal.

**Comment by sazzad16** [comment]
> it started to happen since some version

@andreasdc We started adding these logs only since version 3.6.0. So these exceptions aren't necessarily started happening, these are just started being logged. 

Exceptions used to be hidden before and so users would've almost no info about system health.

**Comment by andreasdc** [comment]
> > it started to happen since some version
> 
> @andreasdc We started adding these logs only since version 3.6.0. So these exceptions aren't necessarily started happening, these are just started being logged.
> 
> Exceptions used to be hidden before and so users would've almost no info about system health.

All right, but is there a way to avoid that? I suppose these exceptions should not happen.

**Comment by sazzad16** [comment]
@andreasdc You may have to debug your system to find out why the connections got broken in the first place. Then you can prevent those exceptions.
