### ISSUE TITLE
Check if key has value associated with

### ISSUE THREAD

**Issue by Elikill58** [redis/jedis#2803]
### Expected behavior

I'm looking for something like `Jedis.has(myKey)`

### Actual behavior

I found [here](https://stackoverflow.com/a/24928900/10952503) that I could use `hgetall`, so I made this :
```java
Map<String, String> val = getJedis().hgetAll(key);
return val != null && !val.isEmpty();
```
But I get this error :
```
com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisDataException: WRONGTYPE Operation against a key holding the wrong kind of value
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.processError(Protocol.java:127) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.process(Protocol.java:161) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.read(Protocol.java:215) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.hgetAll(Jedis.java:848) ~[?:?]
```

#### Jedis version:

The one with `RedisBungee` plugin.

#### Java version:

Java 8u311 (latest of Java 8)

**Comment by sazzad16** [comment]
@Elikill58 I think you're looking for `exists`.

Jedis is a Redis client. No disrespect, but I think you should learn more about Redis and Redis commands first. Thank you.

**Comment by Elikill58** [comment]
Oh yes. You're right. I was thinking about direct method instead of using the same name as command

**Comment by sazzad16** [comment]
[exists](https://redis.io/commands/exists) is a Redis command and that's the direct way to do it.
