### ISSUE TITLE
StackOverflowError when invoke discard method in Transaction in jedis 4.0.1

### ISSUE THREAD

**Issue by leonchen83** [redis/jedis#2815]
### Expected behavior

Write here what you're expecting ...

no exception

### Actual behavior

Write here what happens instead ...

java.lang.StackOverflowError: null
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)

### Steps to reproduce:

above exception happens in when invoke transaction `discard` method and at this time disconnected with redis server. 

we could use `Mockito` to mock above case

reproduce code
```
Jedis jedis = new Jedis("127.0.0.1", 6379);
Connection mock = Mockito.spy(jedis.getConnection());
Mockito.doThrow(new JedisConnectionException("mock")).when(mock).getMany(anyInt());
Transaction trans = new Jedis(mock).multi();
trans.set("a", "a");
trans.set("b", "b");
trans.discard();
```

### Redis / Jedis Configuration

default configuration

**Comment by sazzad16** [comment]
@leonchen83 

First of all, that's a badly written code. Getting a Connection from one Jedis object and creating another Jedis object with that Connection is just an invitation to problems.

---

Jedis.pipelined() and Jedis.multi() may misbehave if used improperly. I consider those methods mostly for legacy softwares.
To play around with Pipeline/Transaction, I would suggest to use them directly.

For example, following code works as what I think is you expected.

```
Connection conn = new Connection("127.0.0.1", 6379);
Connection mock = Mockito.spy(conn);
Mockito.doThrow(new JedisConnectionException("mock")).when(mock).getMany(anyInt());
Transaction trans = new Transaction(mock);  // <-- only difference
trans.set("a", "a");
trans.set("b", "b");
trans.discard();
```

Which generates following error:

```
redis.clients.jedis.exceptions.JedisConnectionException: mock
	at redis.clients.jedis.Transaction.processPipelinedResponses(Transaction.java:40)
	at redis.clients.jedis.TransactionBase.discard(TransactionBase.java:134)
	at redis.clients.jedis.Transaction.discard(Transaction.java:60)
```

---

Lastly, we'll try to work it out from Jedis.multi().

**Comment by leonchen83** [comment]
Hi @sazzad16 
Thanks for your code advise.
the actual code in our system is most like following
```
try(Jedis jedis = new Jedis("127.0.0.1", 6379)) {
    Transaction trans = jedis.multi();
    trans.set("a", "a");
    trans.set("b", "b");
    trans.exec();
}
```

the above code is how to reproduce the problem in our test env.
I think simulate a JedisConnectionException in `Connection` is a way to test Jedis under some complex network conditions. or maybe write a test case base on above code. thanks

**Comment by sazzad16** [comment]
@leonchen83 You can consider changing your system code to

```
try (Connection conn = new Connection("127.0.0.1", 6379)) {
    Transaction trans = new Transaction(conn);
    trans.set("a", "a");
    trans.set("b", "b");
    ....
    trans.discard();
}
```

**Comment by spmason** [comment]
I'm actually seeing `StackOverflowError`s in my app where I _don't_ use Transactions (the endpoint triggering it is just doing a `HGETALL`)

Trace:
```
java.lang.StackOverflowError
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
....... snip ........
	at redis.clients.jedis.TransactionBase.clear(TransactionBase.java:97)
	at redis.clients.jedis.TransactionBase.close(TransactionBase.java:92)
	at redis.clients.jedis.Jedis.resetState(Jedis.java:254)
	at redis.clients.jedis.Transaction.discard(Transaction.java:63)
```

I've downgraded to Jedis 3.7.1 and I'm instead seeing `ReadTimeout` errors, so I'm guessing these StackOverflows are masking those in 4.0.1

**Comment by spmason** [comment]
Hm, there might be a transaction involved actually - Elastic APM says the overflow's are happening for a route where we don't do a transaction but the logs for the socket timeouts are definitely from a point where we use a transaction. Though none of my code calls `.discard`..

Either way, my transaction-using code isn't written in a weird way, just 

```
        var multi = jedis.multi();
        multi.hset(originKeyName, coreMap);

        multi.evalsha(sha, keys, ImmutableList.copyOf(args));

        try {
            var result = multi.exec();

       ........
```

**Comment by leonchen83** [comment]
hi @spmason @sazzad16 
run `multi.exec()` could also failed with `StackOverflowError`
I write a test case to reproduce this issue. hope this case helpful.
```
	@Test
	public void test() {
		try(Jedis jedis = new Jedis("127.0.0.1", 6379)) {
			Connection mock = Mockito.spy(jedis.getConnection());
			Mockito.doThrow(new JedisConnectionException("mock")).when(mock).getMany(anyInt());
			Transaction trans = new Jedis(mock).multi();
			trans.set("a", "a");
			trans.set("b", "b");
			trans.exec();
		} catch (StackOverflowError e) {
			Assertions.fail(e);
		} catch (JedisConnectionException e) {
			// pass
		}
	}
```
