### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR JSON lexer error SPECIAL_EXPECTED at position 1

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2836]
### Expected behavior

Using Jedis 4.0.1 to test Redisearch

### Actual behavior

I used the test code

public void doIt() {
  UnifiedJedis client = new JedisPooled(new HostAndPort("hostIP", 6379));
  Student maya = new Student("Maya", "Jayavant");
  client.jsonSet("student:111", maya);
  
  Student oliwia = new Student("Oliwia", "Jagoda");
  client.jsonSet("student:112", oliwia);
}

### Steps to reproduce:

When I run the program, I get following error

Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR JSON lexer error SPECIAL_EXPECTED at position 1
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getOne(Connection.java:298)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:142)
	at redis.clients.jedis.UnifiedJedis.jsonSet(UnifiedJedis.java:2957)
	at redis.clients.jedis.json.RedisJsonCommands.jsonSet(RedisJsonCommands.java:10)
	at com.example.redisearch.Redisearch2Application.doIt(Redisearch2Application.java:51)
	at com.example.redisearch.Redisearch2Application.main(Redisearch2Application.java:45)

#### Jedis version:
Jedis 4.0.1
#### Redis version:
redis-6.2.4
#### Java version:

JDK 11

Please advise

thanks

Jay

**Comment by sazzad16** [comment]
@shannonantony 

Firstly, `jsonSet` represents [JSON.SET](https://oss.redis.com/redisjson/commands/#jsonset) command which is a RedisJSON command, not RediSearch command.

JSON.SET expects a JSON encoded string, but your `Student` class seems not like that. You have several ways to handle this:

    client.jsonSet("student:111", gson.toJson(maya));

Or,

    client.jsonSetWithEscape("student:111", maya);

You can check the [test file](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java) to learn more. Thanks

**Comment by shannonantony** [comment]
Thanks for your help.

Now I modified the code to be as below

UnifiedJedis client = new JedisPooled(new HostAndPort("10.241.243.151", 6379));
		Student maya = new Student("Maya", "Jayavant");
		// client.jsonSet("student:111", maya);
		client.jsonSet("student:111", ROOT_PATH, maya);
		System.out.println(client.jsonGet("student:111", ROOT_PATH));

		// Student oliwia = new Student("Oliwia", "Jagoda");
		// client.jsonSet("student:112", oliwia);

		client.ftDropIndex("student-index");
		Schema schema = new Schema().addTextField("$.firstName", 1.0).addTextField("$" + ".lastName", 1.0);
		IndexDefinition rule = new IndexDefinition(IndexDefinition.Type.JSON).setPrefixes(new String[] { "student:" });
		client.ftCreate("student-index", IndexOptions.defaultOptions().setDefinition(rule), schema);
		
		
		Query q = new Query("@\\$\\" + ".firstName:maya*");
		SearchResult mayaSearch = client.ftSearch("student-index", q);
		
		List<Document> docs = mayaSearch.getDocuments();
		for (Document doc : docs) {
		   System.out.println(doc);
		}


When I run the program, I get following exceptions

Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: Invalid rule type: JSON
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getOne(Connection.java:298)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:142)
	at redis.clients.jedis.UnifiedJedis.ftCreate(UnifiedJedis.java:2850)
	at com.example.redisearch.Redisearch2Application.doIt(Redisearch2Application.java:62)
	at com.example.redisearch.Redisearch2Application.main(Redisearch2Application.java:46)


Please let me know your thoughts

thanks

Jay

**Comment by sazzad16** [comment]
Ref https://github.com/RediSearch/RediSearch/issues/2532

**Comment by shannonantony** [comment]
Hi,

I am running below function. Do you know what is wrong with my query, I am getting result size = 0. I am following the example at https://github.com/redis/jedis/blob/master/docs/redisjson.md

thanks

Jay

public void doIt1() {
		Gson gson = new Gson();
		UnifiedJedis client = new JedisPooled(new HostAndPort("10.241.243.151", 6379));

		// JedisCluster client = new JedisCluster(sentinels);

		Student maya = new Student("Maya", "Jayavant");
		// client.jsonSet("student:111", maya);
		//client.jsonSet("student:111", gson.toJson(maya));
		client.jsonSetWithEscape("student:111", maya);
		// client.jsonSet("student:111", ROOT_PATH, maya);
		System.out.println(client.jsonGet("student:111"));

		// Student oliwia = new Student("Oliwia", "Jagoda");
		// client.jsonSet("student:112", oliwia);

		client.ftDropIndex("student-index");
		Schema schema = new Schema().addTextField("$.firstName", 1.0).addTextField("$" + ".lastName", 1.0);
		IndexDefinition rule = new IndexDefinition(IndexDefinition.Type.JSON).setPrefixes(new String[] { "student:" });
		client.ftCreate("student-index", IndexOptions.defaultOptions().setDefinition(rule), schema);

		Query q = new Query("@\\$\\" + ".firstName:Maya*");
		// Query q = new Query();
		SearchResult mayaSearch = client.ftSearch("student-index", q);

		System.out.println("result size" + mayaSearch.getTotalResults());

		/*
		 * List<Document> docs = mayaSearch.getDocuments(); for (Document doc : docs) {
		 * System.out.println(doc); }
		 */
	}

**Comment by sazzad16** [comment]
First create index, then insert, then query. Check if this works.

**Comment by shannonantony** [comment]
Great. thanks a lot. it works
