### ISSUE TITLE
Jedis connect failed when using dns resolver in jedis 4.1.0

### ISSUE THREAD

**Issue by leonchen83** [redis/jedis#2848]
### Expected behavior

Write here what you're expecting ...

connect success

### Actual behavior

Write here what happens instead ...

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccsefulHost(DefaultJedisSocketFactory.java:62)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:85)
	at redis.clients.jedis.Connection.connect(Connection.java:180)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:152)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:135)
	at redis.clients.jedis.Jedis.ping(Jedis.java:353)
	at cn.nextop.gadget.redis.Main.main(Main.java:29)
	Suppressed: java.net.SocketTimeoutException: connect timed out
		at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
		at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
		at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
		at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
		at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
		at java.base/java.net.Socket.connect(Socket.java:591)
		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccsefulHost(DefaultJedisSocketFactory.java:65)
		... 6 more
	Suppressed: java.net.SocketException: Socket closed
		at java.base/java.net.PlainSocketImpl.checkAndReturnNativeFD(PlainSocketImpl.java:307)
		at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:91)
		at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
		at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
		at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
		at java.base/java.net.Socket.connect(Socket.java:591)
		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccsefulHost(DefaultJedisSocketFactory.java:65)
		... 6 more
```
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
```
try(Jedis jedis = new Jedis("dev-erebor.nextop.cn", 6379)) {
	System.out.println(jedis.ping()); // failed
}
```

dns resolver
```
InetAddress[] hosts = InetAddress.getAllByName("dev-erebor.nextop.cn");
for (InetAddress address : hosts) {
	System.out.println(address);
}

console print
dev-erebor.nextop.cn/240e:60c:2801:1:0:0:c0a8:1e9
dev-erebor.nextop.cn/192.168.1.233
```

when connect to `240e:60c:2801:1:0:0:c0a8:1e9` failed then connect to `192.168.1.233` also failed
but use IP address directly then connect success.
```
try(Jedis jedis = new Jedis("192.168.1.233", 6379)) {
	System.out.println(jedis.ping()); // success
}
```
### Redis / Jedis Configuration

redis.conf
```
bind 192.168.1.233
```

**Comment by yangbodong22011** [comment]
@leonchen83 Thanks for your report, I can reproduce the issue, and the reason seems to be that the second connection fails because the socket state is changed to `closed` after the first failure.

**Comment by why168** [comment]
see https://github.com/redis/jedis/pull/2849#issuecomment-2049478503
