### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2851]
### Actual behavior
Occasionally I get following error while loading the data into Redis

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
        at redis.clients.jedis.Protocol.process(Protocol.java:158)
        at redis.clients.jedis.Protocol.read(Protocol.java:223)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
        at redis.clients.jedis.Connection.getIntegerReply(Connection.java:294)
        at redis.clients.jedis.Jedis.hset(Jedis.java:838)

#### Jedis version:
3.0
#### Redis version:
6.2.4
#### Java version:
Java 11

Can you please let me know how do I fix it. I could not find anything wrong with Redis.

thanks

Jay

**Comment by Akaame** [comment]
Are you trying to connect to a remote Redis (like GCP Memorystore or on-premise VM)? This really looks just like a network issue?

Can you share your env setup and the code if possible?

**Comment by sazzad16** [comment]
Closing due to inactivity.
