### ISSUE TITLE
Upgrade from 3.7.0 to 4.1.1 leads to ClassNotFoundException: redis/clients/jedis/GeoUnit

### ISSUE THREAD

**Issue by knyttl** [redis/jedis#2860]
### Expected behavior

We upgraded to 4.1.1 and we are seeing `ClassNotFoundException: redis/clients/jedis/GeoUnit` exceptions since.

```
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/GeoUnit
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.<clinit>(JedisConnectionFactory.java:93)
	at net.goout.config.RedisCacheConfig.jedisConnectionFactory(RedisCacheConfig.kt:107)
	at net.goout.config.RedisCacheConfig$$EnhancerBySpringCGLIB$$677e4e12.CGLIB$jedisConnectionFactory$2(<generated>)
	at net.goout.config.RedisCacheConfig$$EnhancerBySpringCGLIB$$677e4e12$$FastClassBySpringCGLIB$$5166693e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at net.goout.config.RedisCacheConfig$$EnhancerBySpringCGLIB$$677e4e12.jedisConnectionFactory(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 95 more
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.GeoUnit
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
	... 107 more
```

### Actual behavior

Hopefully, this should still work

### Redis / Jedis Configuration

- redis.clients:jedis:4.1.1
- org.springframework.data:spring-data-redis:2.6.1

#### Java version:

JDK17-temurin

**Comment by sazzad16** [comment]
[Jedis 3 to Jedis 4 Breaking Changes](https://github.com/redis/jedis/blob/master/docs/3to4.md)

> - The following classes have been moved to the redis.clients.jedis.args package.
>   - BitOP
>   - GeoUnit
>   - ListPosition

@knyttl I would strongly suggest to let spring-data-redis team to upgrade to Jedis 4. Thank you.

**Comment by knyttl** [comment]
Tahnks for info. I guess https://github.com/spring-projects/spring-data-redis/issues/2212 needs to be resolved then.
