### ISSUE TITLE
xinfoStreamFull ClassCastException if there are pending messages

### ISSUE THREAD

**Issue by martin-nagy** [redis/jedis#2987]
### Actual behavior

If there are pending messages in a stream this exception is thrown during the `redis.clients.jedis.Jedis#xinfoStreamFull` call:

```java
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [B (java.util.ArrayList and [B are in module java.base of loader 'bootstrap')
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$20.build(BuilderFactory.java:334)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$20.build(BuilderFactory.java:325)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory.createMapFromDecodingFunctions(BuilderFactory.java:1464)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory.access$100(BuilderFactory.java:24)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$61.build(BuilderFactory.java:1380)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$61.build(BuilderFactory.java:1348)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory.createMapFromDecodingFunctions(BuilderFactory.java:1464)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory.access$100(BuilderFactory.java:24)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$62.build(BuilderFactory.java:1421)
  at deployment.ROOT.war//redis.clients.jedis.BuilderFactory$62.build(BuilderFactory.java:1394)
  at deployment.ROOT.war//redis.clients.jedis.Connection.executeCommand(Connection.java:123)
  at deployment.ROOT.war//redis.clients.jedis.Jedis.xinfoStreamFull(Jedis.java:9376)
```
Probably the problem is with this class: `redis.clients.jedis.BuilderFactory#STREAM_GROUP_FULL_INFO_LIST`.
The `StreamGroupFullInfo.PENDING` should not be a simple `STRING_LIST`, it should be a more complex structure (i.e. list of list of strings).

### Steps to reproduce:

1. create a redis stream
2. create a redis stream consumer
3. XADD a message
4. XREADGROUP the message with NOACK
5. call `redis.clients.jedis.Jedis#xinfoStreamFull` on the redis stream

**Comment by martin-nagy** [comment]
Thank you for the fast response
