### ISSUE TITLE
NumberFormatException thrown when executing graph query that returns infinity

### ISSUE THREAD

**Issue by InverseIntegral** [redis/jedis#3010]
### Expected behavior

I would expect the query to run without any problem.

### Actual behavior
An exception is thrown:

```
Caused by: java.lang.NumberFormatException: For input string: "inf"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at redis.clients.jedis.graph.ResultSetBuilder.deserializeScalar(ResultSetBuilder.java:259)
	at redis.clients.jedis.graph.ResultSetBuilder.parseRecords(ResultSetBuilder.java:155)
	at redis.clients.jedis.graph.ResultSetBuilder.build(ResultSetBuilder.java:62)
	at redis.clients.jedis.graph.ResultSetBuilder.build(ResultSetBuilder.java:23)
	at redis.clients.jedis.Response.build(Response.java:62)
	at redis.clients.jedis.Response.get(Response.java:38)
	at redis.clients.jedis.TransactionBase.exec(TransactionBase.java:141)
	at redis.clients.jedis.Transaction.exec(Transaction.java:47)
```

### Steps to reproduce:

Run the following to reproduce the exception:
```java
try (Jedis resource = pool.getResource()) {
    try (Transaction transaction = new Transaction(resource)) {
        transaction.graphQuery("db", "RETURN 10^100000");
        transaction.exec();
    }
}
```

RedisGraph returns `inf` / `-inf` which cannot be parsed by `Double.parseDouble`. Similarly, the same thing happens with `NaN` values.

### Redis / Jedis Configuration
**Jedis version**: 4.2.3
**Redis version**: 6.2.6
**Java version**: 11

**Comment by sazzad16** [comment]
@InverseIntegral acknowledged. Thanks for the test, it's really helpful.
