### ISSUE TITLE
How to create a JSONARRAY by jsonSet

### ISSUE THREAD

**Issue by supery-chen** [redis/jedis#3016]
### Expected behavior

![image](https://user-images.githubusercontent.com/54849153/172512390-fe838d83-b672-4fe9-9ee0-d6847c86ff73.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/54849153/172512461-98b85e6c-7685-4de7-ba4d-0ed714a93bd8.png)

**Comment by sazzad16** [comment]
@supery-chen Please post text.

**Comment by supery-chen** [comment]
> @supery-chen Please post text.

my test code

```java
import org.junit.Test;
import redis.clients.jedis.JedisPooled;

import java.util.Collections;
import java.util.List;

public class JedisTest {

    @Test
    public void test() {
        JedisPooled jedisPooled = new JedisPooled();
        TestObj a = new TestObj("a");
        List<TestObj> list = Collections.singletonList(a);
        String resp = jedisPooled.jsonSet("test", list);
        System.out.println(resp);
    }

    private static class TestObj {
        private String a;

        public TestObj(String a) {
            this.a = a;
        }

        public String getA() {
            return a;
        }

        public void setA(String a) {
            this.a = a;
        }
    }

}
```

**Comment by supery-chen** [comment]
Exception

```
redis.clients.jedis.exceptions.JedisDataException: expected value at line 1 column 2

	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getOne(Connection.java:298)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:148)
	at redis.clients.jedis.UnifiedJedis.jsonSet(UnifiedJedis.java:3529)
	at redis.clients.jedis.json.RedisJsonCommands.jsonSet(RedisJsonCommands.java:10)
	at com.superychen.JedisTest.test(JedisTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by sazzad16** [comment]
@supery-chen `jedisPooled.jsonSetLegacy("test", list);` produces the result you want.

**Comment by supery-chen** [comment]
@sazzad16 Thanks for your reply.

after reading the source code below, I override my TestObj's toString method to return a json string, and `jedisPooled.jsonSet("test", list)` works now

```java
public class CommandObjects {

  public final CommandObject<String> jsonSet(String key, Path2 path, Object object) {
    return new CommandObject<>(commandArguments(JsonCommand.SET).key(key).add(path).add(object), BuilderFactory.STRING);
  }

  public final CommandObject<String> jsonSet(String key, Path path, Object pojo) {
    return new CommandObject<>(commandArguments(JsonCommand.SET).key(key).add(path).add(GSON.toJson(pojo)), BuilderFactory.STRING);
  }

}
```

```java
public class CommandArguments implements Iterable<Rawable> {

  public CommandArguments add(Object arg) {
    if (arg instanceof Rawable) {
      args.add((Rawable) arg);
    } else if (arg instanceof byte[]) {
      args.add(RawableFactory.from((byte[]) arg));
    } else if (arg instanceof String) {
      args.add(RawableFactory.from((String) arg));
    } else if (arg instanceof Boolean) {
      args.add(RawableFactory.from(Integer.toString((Boolean) arg ? 1 : 0)));
    } else {
      if (arg == null) {
        throw new IllegalArgumentException("null is not a valid argument.");
      }
      args.add(RawableFactory.from(String.valueOf(arg)));
    }
    return this;
  }

}
```
