### ISSUE TITLE
JedisPooled(config, url) constructor fails with -1 port

### ISSUE THREAD

**Issue by nosideeffects** [redis/jedis#3047]
The second available constructor with the following signature always fails: 
```
public JedisPooled(final GenericObjectPoolConfig<Connection> poolConfig, final String url)
```

### Expected behavior

It should default to using `Protocol.DEFAULT_PORT`

### Actual behavior
  
Attempting to create connection for a `JedisPooled` created with the above constructor throws the follow exception stack:
```
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.Connection.connect(Connection.java:180) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.Connection.<init>(Connection.java:53) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:71) ~[jedis-4.2.3.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[commons-pool2-2.11.1.jar:2.11.1]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:34) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:28) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:54) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:148) ~[jedis-4.2.3.jar:?]
	at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:585) ~[jedis-4.2.3.jar:?]
	Suppressed: java.lang.IllegalArgumentException: port out of range:-1
		at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:152) ~[?:?]
		at java.net.InetSocketAddress.<init>(InetSocketAddress.java:233) ~[?:?]
		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.Connection.connect(Connection.java:180) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:338) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.Connection.<init>(Connection.java:53) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:71) ~[jedis-4.2.3.jar:?]
		at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[commons-pool2-2.11.1.jar:2.11.1]
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[commons-pool2-2.11.1.jar:2.11.1]
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[commons-pool2-2.11.1.jar:2.11.1]
		at redis.clients.jedis.util.Pool.getResource(Pool.java:34) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:28) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:54) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:148) ~[jedis-4.2.3.jar:?]
		at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:585) ~[jedis-4.2.3.jar:?]
```

### Steps to reproduce:

1. Create `JedisPooled` using the `JedisPooled(config, url)` constructor
2. Attempt to issue any command

#### Jedis version:
4.2.3

#### Redis version:
N/A

#### Java version:
17.0.3

**Comment by sazzad16** [comment]
@nosideeffects Thanks for reporting.

BTW, this is the expected behavior (which is restrictive compared to Jedis 3.x). But this particular constructor is missing relevant JavaDoc.

**Comment by nosideeffects** [comment]
This constructor works as you would expect in version `4.1.1` -- so this is at least a breaking change from that version.

**Comment by sazzad16** [comment]
Yes, the way it was working is considered a bug compared how it should have worked. This is why the change is listed under `Bug Fixes` in [4.2.0 release note](https://github.com/redis/jedis/releases/tag/v4.2.0).

![image](https://user-images.githubusercontent.com/7600764/175047091-b22ea5da-8666-4454-a9e0-4f4aeda99fde.png)

**Comment by sazzad16** [comment]
It was supposed to be part of a [feature + breaking change](https://github.com/redis/jedis/blob/v4.0.0/docs/3to4.md) in Jedis 4.0.0 but mistakenly wasn't.

> ... constructors with a String parameter, and no int parameter only support a URL or URI string.

At the moment of releasing 4.2.0 it seemed logical to tag it as bug. Your suggestion is definitely another way to handle it which was somehow missed. The release note has been updated and we apologize for your inconveniences. At the end of the we are all humans, aren't we?

Cheers! Have a nice day :smiley:

**Comment by nosideeffects** [comment]
Sorry if I am coming across as aggressive, just wanted to be clear that something is definitely off about this constructor.

Can you provide a working example of the constructor in question that does not throw an exception when you try to make use of it?

**Comment by sazzad16** [comment]
There's nothing to be sorry about. It was us who could do better with the release notes.

---

Use the following constructor with `port=6379` or `port=Protocol.DEFAULT_PORT`.
```
public JedisPooled(final GenericObjectPoolConfig<Connection> poolConfig, final String host, final int port)
```

**Comment by nosideeffects** [comment]
That is the constructor we had to change to using, but how would someone use this one?
```
public JedisPooled(final GenericObjectPoolConfig<Connection> poolConfig, final String url)
```

Thanks for the very timely responses!

**Comment by sazzad16** [comment]
`url` should follow following schema:
```
redis://<<USER>:<PASSWORD>>@<HOST>:<PORT>/<DATABASE>
```
Example:

https://github.com/redis/jedis/blob/d55473c8bb54fce76b71691f87a37fcf70f06641/src/test/java/redis/clients/jedis/JedisPooledTest.java#L61

**Comment by sazzad16** [comment]
[GENERAL COMMENT]
Issue resolved by https://github.com/redis/jedis/commit/ba63b5d02459c38de3c42e63d866031f8a156122

**Comment by sazzad16** [comment]
Resolved Javadoc (for future reference): https://github.com/redis/jedis/blob/ba63b5d02459c38de3c42e63d866031f8a156122/src/main/java/redis/clients/jedis/JedisPooled.java#L74-L87
