### ISSUE TITLE
jedispool was closed inexplicably

### ISSUE THREAD

**Issue by xiaogengi** [redis/jedis#3099]
！！！
The will appear after running for a while，
did not close manually
！！！

### Expected behavior
 java.lang.IllegalStateException: Pool not open

### Actual behavior
Caused by: java.lang.IllegalStateException: Pool not open
at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
at redis.clients.util.Pool.getResource(Pool.java:49)

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Jedis version:
2.9.3

#### Redis version:
6.2.5

#### Java version:
1.8

**Comment by sazzad16** [comment]
@xiaogengi This is not reproducible. Sorry but can't help much.

You may try an updated version like 4.2.3 or 3.9.0.

**Comment by xiaogengi** [comment]
> @xiaogengi This is not reproducible. Sorry but can't help much.
> 
> You may try an updated version like 4.2.3 or 3.9.0.

thanks
