### ISSUE TITLE
hey i got this error i tried compiling it too

### ISSUE THREAD

**Issue by Xteri08** [redis/jedis#3133]
19:30:48 [WARNING] Could not load plugin from file plugins/jedis-4.3.0-m1.jar
java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
    at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:380)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by yangbodong22011** [comment]
@Xteri08 Can you provide steps, commands, environment to reproduce this issue?

**Comment by sazzad16** [comment]
Closed due to inactivity.
