### ISSUE TITLE
JedisCluster: 'Could not get a resource since the pool is exhausted' and 'Timeout waiting for idle object'

### ISSUE THREAD

**Issue by choice** [redis/jedis#3141]
### Expected behavior

There is no abnormal

I've also encountered the 'Could not get a resource since the pool is exhausted' situation. 
I use "JedisCluster". RedisCluster indicates three master and three slave modes.

Currently, the number of connections of each node is about 600

# Clients
connected_clients:590
client_recent_max_input_buffer:4
client_recent_max_output_buffer:0
blocked_clients:0

'client list ' Data
Lots of 'ping' and 'NULL'
id=7587146 addr=*.*.*.*:60918 fd=50 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=NULL
id=7587148 addr=*.*.*.*:60874 fd=404 name= age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=7586552 addr=*.*.*.*:61707 fd=610 name= age=88 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client

### Actual behavior

It's abnormal

Caused by: redis.clients.jedis.exceptions.JedisExhaustedPoolException: Could not get a resource since the pool is exhausted

	at redis.clients.jedis.util.Pool.getResource(Pool.java:53) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:95) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:102) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:45) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.eval(JedisCluster.java:1879) ~[jedis-3.3.0.jar!/:?]
	... 139 more

Caused by: java.util.NoSuchElementException: Timeout waiting for idle object

	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:444) ~[commons-pool2-2.8.0.jar!/:2.8.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354) ~[commons-pool2-2.8.0.jar!/:2.8.0]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:95) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:102) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:45) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.eval(JedisCluster.java:1879) ~[jedis-3.3.0.jar!/:?]
	... 139 more

### Steps to reproduce:

Not locally reproducible

### Redis / Jedis Configuration

I made it my own

JedisPoolConfig config = new JedisPoolConfig();

	config.setMaxTotal(500);
	config.setMaxIdle(500);
	config.setMinIdle(100);

	config.setTestOnBorrow(false);
	config.setTestOnReturn(false);
	config.setTestOnCreate(true);
	config.setMaxWaitMillis(5000);

	for (String hostAndPort : hostAndPorts) {
	      if (!hostAndPort.contains(":")) {
		    throw new ServiceException("[配置校验] Redis Cluster Node 配置错误");
	      }
	      jedisClusterNodes.add(new HostAndPort(hostAndPort.split(":")[0], Integer.parseInt(hostAndPort.split(":")[1])));
	}
	jedisCluster = new JedisCluster(jedisClusterNodes, timeout, 5000 , 10 , password, config);

And the default configuration

public class JedisPoolConfig extends GenericObjectPoolConfig {
    public JedisPoolConfig() {
        this.setTestWhileIdle(true);
        this.setMinEvictableIdleTimeMillis(60000L);
        this.setTimeBetweenEvictionRunsMillis(30000L);
        this.setNumTestsPerEvictionRun(-1);
    }
}

 
#### Java version: 1.8.0_181

**Comment by choice** [comment]
Does JedisCluster manage and close connections by itself?

If it is closed automatically,the number of connections to each node of RedisCluster is about 600.  Is it normal?


private T runWithRetries(int slot, int attempts, boolean tryRandomNode, JedisRedirectionException redirect) {
        if (attempts <= 0) {
            throw new JedisClusterMaxAttemptsException("No more cluster attempts left.");
        } else {
            Jedis connection = null;

            Object var7;
            try {
                if (redirect != null) {
                    connection = this.connectionHandler.getConnectionFromNode(redirect.getTargetNode());
                    if (redirect instanceof JedisAskDataException) {
                        connection.asking();
                    }
                } else if (tryRandomNode) {
                    connection = this.connectionHandler.getConnection();
                } else {
                    connection = this.connectionHandler.getConnectionFromSlot(slot);
                }

                Object var6 = this.execute(connection);
                return var6;
            } catch (JedisNoReachableClusterNodeException var13) {
                throw var13;
            } catch (JedisConnectionException var14) {
                this.releaseConnection(connection);
                connection = null;
                if (attempts <= 1) {
                    this.connectionHandler.renewSlotCache();
                }

                var7 = this.runWithRetries(slot, attempts - 1, tryRandomNode, redirect);
            } catch (JedisRedirectionException var15) {
                if (var15 instanceof JedisMovedDataException) {
                    this.connectionHandler.renewSlotCache(connection);
                }

                this.releaseConnection(connection);
                connection = null;
                var7 = this.runWithRetries(slot, attempts - 1, false, var15);
                return var7;
            } finally {
                this.releaseConnection(connection);
            }

            return var7;
        }
       
 
 private void releaseConnection(Jedis connection) {
        if (connection != null) {
            connection.close();
        }
    }

**Comment by choice** [comment]
The problem escalates again

redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.

2022.09.19 16:34:08|ERROR|com.*******GlobalExceptionHandler|bindException()|Exception:
redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:124) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:25) ~[jedis-3.3.0.jar!/:?]
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:190) ~[jedis-3.3.0.jar!/:?]

**Comment by sazzad16** [comment]
@choice Please try a newer version of Jedis; i.e. 4.3.0-m1 / 4.2.3 / 3.9.0

**Comment by choice** [comment]
> @choice Please try a newer version of Jedis; i.e. 4.3.0-m1 / 4.2.3 / 3.9.0

At present, the Linux server handle has been adjusted, the deep pressure test of the project has been conducted, and new JedisPool data has been configured.  The production environment has returned to normal.

As for the new version, I have no free time to explore at present.  I will explore the use of the new version after I finish my work.
Thank you very much for your reply.  OO (●'◡'●)
