### ISSUE TITLE
ftSearch fails with NullPointerException when reading a json element with null value

### ISSUE THREAD

**Issue by shkediy** [redis/jedis#3147]
When returning a field with null value from a json search, it throws a NullPointeException.
It works fine with redis-cli
To reproduce:

FT.CREATE acct ON JSON PREFIX 1 acct: SCHEMA $.name AS name TEXT $.phone AS phone TEXT
JSON.SET acct:2 $ '{"id": "2", "name": "Jane", "phone": null}'
FT.SEARCH acct '@name:jane' return 1 $.phone
1) (integer) 1
2) "acct:2"
3) 1) "$.phone"
   2) (nil)

Query q = new Query("(@name:Jane)"); // criteria (@phone:7201112233) works fine
String[] selClause = new String[]{"$.phone"};
q.returnFields(selClause);
SearchResult srchRslt = client.ftSearch("acct", q); 

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:577)
	at redis.clients.jedis.util.SafeEncoder.encode(SafeEncoder.java:35)
	at redis.clients.jedis.search.Document.load(Document.java:58)
	at redis.clients.jedis.search.SearchResult$SearchResultBuilder.build(SearchResult.java:78)
	at redis.clients.jedis.search.SearchResult$SearchResultBuilder.build(SearchResult.java:31)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:148)
	at redis.clients.jedis.UnifiedJedis.ftSearch(UnifiedJedis.java:3432)
	at com.redislabs.SearchTest.proveNpBugInJedis(SearchTest.java:22)
	at com.redislabs.SearchTest.main(SearchTest.java:37)

Looks like the Document.load method calls SafeEncoder.encode with null (because the value is null).

**Comment by sazzad16** [comment]
@shkediy Thanks for reporting. Even though we have tests with null but neither Gson (by default) nor JSONObject stores null. That's why the issue was not caught.
