### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: expected value at line 1 column 1

### ISSUE THREAD

**Issue by sergey-morenets** [redis/jedis#3199]
I took this example from the official documentation: https://github.com/redis/jedis/blob/master/docs/redisjson.md
And exception surprised me because I used the latest versions of Redis and Jedis.

### Expected behavior

 No errors should be raised

### Actual behavior

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: expected value at line 1 column 1
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
```

### Steps to reproduce:

```
		try (JedisPooled client = new JedisPooled("localhost", 6379)) {
			Student maya = new Student("Maya", "Jayavant");
			client.jsonSet("student:111", maya);
		}
```

```
public class Student {
    private String firstName;
    private String lastName;

    public Student(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }
}
```

#### Jedis version:

4.3.1

#### Redis version:

7.0.0. RC4

#### Java version:

JDK 19.0.1

**Comment by sazzad16** [comment]
@sergey-morenets Thank you for reporting.
