### ISSUE TITLE
Startup operation error Caused by: java.lang.NoSuchMethodError: 'void redis.clients.jedis.JedisPoolConfig.setMinEvictableIdleTime(java.time.Duration)'

### ISSUE THREAD

**Issue by LJFDBXJ** [redis/jedis#3251]
Caused by: java.lang.NoSuchMethodError: 'void redis.clients.jedis.JedisPoolConfig.setMinEvictableIdleTime(java.time.Duration)'
	at redis.clients.jedis.JedisPoolConfig.<init>(JedisPoolConfig.java:11) ~[jedis-4.3.0.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisClientConfiguration$DefaultJedisClientConfigurationBuilder.<init>(JedisClientConfiguration.java:272) ~[spring-data-redis-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisClientConfiguration$DefaultJedisClientConfigurationBuilder.<init>(JedisClientConfiguration.java:264) ~[spring-data-redis-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisClientConfiguration.builder(JedisClientConfiguration.java:114) ~[spring-data-redis-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at com.ljfdbxj.api.core.config.RedisConfig.redisConnectionFactory(RedisConfig.java:52) ~[classes/:na]
	at com.ljfdbxj.api.core.config.RedisConfig$$EnhancerBySpringCGLIB$$d85c80af.CGLIB$redisConnectionFactory$1(<generated>) ~[classes/:na]
	at com.ljfdbxj.api.core.config.RedisConfig$$EnhancerBySpringCGLIB$$d85c80af$$FastClassBySpringCGLIB$$7dd0712f.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at com.ljfdbxj.api.core.config.RedisConfig$$EnhancerBySpringCGLIB$$d85c80af.redisConnectionFactory(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 76 common frames omitted

public class JedisPoolConfig extends GenericObjectPoolConfig<Jedis> {
    public JedisPoolConfig() {
        this.setTestWhileIdle(true);
        this.setMinEvictableIdleTime(Duration.ofMillis(60000L));
        this.setTimeBetweenEvictionRuns(Duration.ofMillis(30000L));
        this.setNumTestsPerEvictionRun(-1);
    }
}

# The two methods are not found in the parent class
##   this.setTimeBetweenEvictionRuns(Duration.ofMillis(30000L));

i try use custom 
public class JedisConfig extends GenericObjectPoolConfig<Jedis> {
    public JedisConfig() {
        this.setTestWhileIdle(true);
        this.setMinEvictableIdleTimeMillis(60000L);
        this.setTimeBetweenEvictionRunsMillis(30000L);
        this.setNumTestsPerEvictionRun(-1);
    }
}

but still report this error

**Comment by sazzad16** [comment]
Use Jedis 2.x (i.e. `2.9.3` or `2.10.2`) with spring-data-redis-2.1.9.RELEASE

**Comment by LJFDBXJ** [comment]
I know it's OK to use the lower version. Why is this version cant

**Comment by sazzad16** [comment]
Because commons-pool library in your classpath is not updated enough.

**Comment by LJFDBXJ** [comment]
Thank you for your answer, brother ,I hope everything goes well with you

**Comment by LJFDBXJ** [comment]
Thank you for your answer, brother ,I hope everything goes well with you
