### ISSUE TITLE
NoSuchMethodError: redis.clients.jedis.Jedis.sendCommand

### ISSUE THREAD

**Issue by JzHuang4** [redis/jedis#3295]
### Expected behavior

Send customized command using Jedis

### Actual behavior

var jedisPool = new JedisService("").jedisPool
var jedisRead = jedisPool.getResource
var get_ori = redis.clients.jedis.Protocol.Command.GET
println(this.jedisRead.sendCommand(get_ori, key))

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. inialize a Jedis instance
2. produce a command using redis.clients.jedis.Protocol.Command
3. jedis.sendCommand(cmd, args)

#### Jedis version:
3.7.1
#### Java version:
1.8

**Comment by sazzad16** [comment]
What is `args`?

Also add detailed stacktrace.

**Comment by JzHuang4** [comment]
PONG
null
Exception in thread "main" java.lang.NoSuchMethodError: redis.clients.jedis.Client.sendCommand(Lredis/clients/jedis/commands/ProtocolCommand;[Ljava/lang/String;)V
        at org.didi.map.point.RealTimeMainPipeline$.delayedEndpoint$org$didi$map$point$RealTimeMainPipeline$1(RealTimeMainPipeline.scala:42)
        at org.didi.map.point.RealTimeMainPipeline$delayedInit$body.apply(RealTimeMainPipeline.scala:10)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.didi.map.point.RealTimeMainPipeline$.main(RealTimeMainPipeline.scala:10)
        at org.didi.map.point.RealTimeMainPipeline.main(RealTimeMainPipeline.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by JzHuang4** [comment]
> What is `args`?
> 
> Also add detailed stacktrace.

args mean the input arguments and the whole stacktrace shows as above.

**Comment by sazzad16** [comment]
Scala can't handle varags. Instead of a String, pass a String array.

**Comment by JzHuang4** [comment]
> Scala can't handle varags. Instead of a String, pass a String array.

I have tried this way. Do all these things in a java class and just import and use the method in Scala main function.

**Comment by JzHuang4** [comment]
> PONG null Exception in thread "main" java.lang.NoSuchMethodError: redis.clients.jedis.Client.sendCommand(Lredis/clients/jedis/commands/ProtocolCommand;[Ljava/lang/String;)V at org.dd.RealTimeMainPipeline$.delayedEndpoint$org$didi$map$point$RealTimeMainPipeline$1(RealTimeMainPipeline.scala:42) at org.didi.map.point.RealTimeMainPipeline$delayedInit$body.apply(RealTimeMainPipeline.scala:10) at scala.Function0$class.apply$mcV$sp(Function0.scala:34) at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) at scala.App$$anonfun$main$1.apply(App.scala:76) at scala.App$$anonfun$main$1.apply(App.scala:76) at scala.collection.immutable.List.foreach(List.scala:392) at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) at scala.App$class.main(App.scala:76) at org.dd.RealTimeMainPipeline$.main(RealTimeMainPipeline.scala:10) at org.dd.RealTimeMainPipeline.main(RealTimeMainPipeline.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52) at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851) at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167) at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195) at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86) at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935) at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
