### ISSUE TITLE
jedis 4.3.0 error while validaing pooled connection object

### ISSUE THREAD

**Issue by jk2K** [redis/jedis#3314]
### Expected behavior

no error

### Actual behavior

error occurs

```plain
12023-03-07 00:00:00 [timerTask-0] ERROR redis.clients.jedis.ConnectionFactory.v
alidateobject: 103] Error while validating pooled Connection object.
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of strea
m.
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream
• java: 205)
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.
ava: 46)
        at redis.clients.jedis.Protocol.process (Protocol.java: 126)
        at redis.clients.jedis.Protocol.read (Protocol.java: 192)
        at redis.clients.jedis.connection.readProtocolWithCheckingBroken(Connect
ion. java: 316)
        at redis.clients.jedis.connection.getstatusCodeReply(Connection.java:243
        at redis.clients.jedis.connection.ping (Connection.java: 400)
        at redis.clients.jedis.ConnectionFactory.validateobject(ConnectionFactor
V. java: 101)
        at org.apache.commons.pool2.impl.GenericobjectPool.borrowobject(Generico
bjectPool. java: 479)
        at org.apache.commons.pool2.impl.GenericobjectPool.borrowobject(Generico
bjectPool. java: 356)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:34)
        at redis.clients.jedis.connectionPool.getResource(ConnectionPool.java:28
        at redis.clients.jedis.providers.ClusterConnectionProvider.getconnection
Fromslot (ClusterConnectionProvider.java: 124)
        at redis.clients.jedis.providers.ClusterConnectionProvider.getconnection
(ClusterConnectionProvider.java:80)
        at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(C
lusterCommandExecutor.java:54)
        at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:167
)
        at redis.clients.jedis.UnifiedJedis.setnx(UnifiedJedis.java:684)
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration

```java
Set<HostAndPort> jedisClusterNodes = new HashSet<>();
redisProperties.getHosts().forEach(element -> jedisClusterNodes.add(new HostAndPort(element.getHost(), element.getPort())));
GenericObjectPoolConfig<Connection> jedisPoolConfig = new GenericObjectPoolConfig<>();
jedisPoolConfig.setMaxWaitMillis(3000);
jedisPoolConfig.setTestOnBorrow(true);
jedisPoolConfig.setTestOnReturn(true);
JedisCluster jedis = new JedisCluster(jedisClusterNodes, 20000, 10000, 1, redisProperties.getPassword(), jedisPoolConfig);
```

#### Jedis version:
4.3.0

#### Redis version:
7.0.4

#### Java version:
openjdk 1.8.0_342

**Comment by sazzad16** [comment]
This is not an error[1] but an error log. Getting such logs now and then is considered acceptable. The post doesn't mention the frequency of such logs to consider otherwise.

[1] In the sense that it is not an exception that is being thrown and hampering code flow.

**Comment by sazzad16** [comment]
Closed due to inactivity.
