### ISSUE TITLE
[redis.clients.jedis.JedisFactory] Error while validating pooled Jedis object.

### ISSUE THREAD

**Issue by Charlito33** [redis/jedis#3479]
### Expected behavior

No error when using ``Jedis#subscribe()`` on another Thread.

### Actual behavior

Jedis returns an error :
```logs
[11:39:48 ERROR]: [redis.clients.jedis.JedisFactory] Error while validating pooled Jedis object.
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [B (java.util.ArrayList and [B are in module java.base of loader 'bootstrap')
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:262) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.Jedis.ping(Jedis.java:331) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:206) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:1033) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.util.Pool.returnResource(Pool.java:51) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:388) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:17) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at redis.clients.jedis.Jedis.close(Jedis.java:289) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at fr.charlito33.rednetlib.RedNetLib$RedNetLibSync.run(RedNetLib.java:150) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at fr.charlito33.rednetlib.RedNetLib$RedNetLibSync.listen(RedNetLib.java:161) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at net.evershell.evereconomy.playershop.sync.PlayerShopSync.lambda$init$4(PlayerShopSync.java:39) ~[EverEconomy-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce:

1. Create a JedisPool
2. Use ``JedisPool#getResource()`` to get a Jedis Instance
3. Pass this Redis instance to a thread
4. Subscribe with ``Jedis#subscribe()`` in this thread
5. Wait for the subscriber to receive data

or

1. Create a JedisPool
2. Create a new Thread
3. Use ``JedisPool#getResource()`` to get a Jedis Instance in this thread
4. Subscribe with ``Jedis#subscribe()`` in this thread
5. Wait for the subscriber to receive data

### Redis / Jedis Configuration

```java
jedisPoolConfig.setMaxTotal(128);
jedisPoolConfig.setMaxIdle(128);
jedisPoolConfig.setMinIdle(16);
jedisPoolConfig.setTestOnBorrow(true);
jedisPoolConfig.setTestOnReturn(true);
jedisPoolConfig.setTestWhileIdle(true);
jedisPoolConfig.setMinEvictableIdleTime(Duration.ofSeconds(60));
jedisPoolConfig.setTimeBetweenEvictionRuns(Duration.ofSeconds(30));
jedisPoolConfig.setNumTestsPerEvictionRun(3);
jedisPoolConfig.setBlockWhenExhausted(true);
```

#### Jedis version:

4.4.3

#### Redis version:

7.0.11

#### Java version:

Java 17, running Jedis through a Minecraft Purpur Server

**Comment by sazzad16** [comment]
You shouldn't `close()` Jedis object (or use that in try-with-resources) while it is in subscription (`subscribe()`) mode.

**Comment by Charlito33** [comment]
Seems to be working !
Thanks for your help !
