### ISSUE TITLE
Exception: JedisDataException: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by madhub05** [redis/jedis#3489]
Hello All,
I am using redis.clients:jedis:4.4.3' and connecting to azure redis cache it is working fine most of the time but getting below NOAUTH issue Intermittently  

"Result: Failure
Exception: JedisDataException: NOAUTH Authentication required.
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
	at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
	at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:335)
	at redis.clients.jedis.Connection.getOne(Connection.java:317)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:131)
	at redis.clients.jedis.Jedis.exists(Jedis.java:5020)
"

**Comment by sazzad16** [comment]
It's not clear from where the Jedis object is received.

If it is coming from a pool and you're usually getting operable objects from that pool, check if references of some objects are being hold and closed multiple times. First close() returns the object to the pool but second close() could clear its state (i.e. remove AUTH, etc).

**Comment by madhub05** [comment]
Yes, it is coming from pool and we are closing properly after use , please find the below sample code which we are using

public class  wxy{
 public static JedisPool getJedisPool() {
        if (null == jedisPool) {
            jedisPool = new JedisPool(buildPoolConfig(), cacheHostname,
                   6380, Protocol.DEFAULT_TIMEOUT, cachekey, true);
        }
        return jedisPool;
    }

    private static JedisPoolConfig buildPoolConfig() {
        final JedisPoolConfig poolConfig = new JedisPoolConfig();
        return poolConfig;
    }
}
	
	public class xyz{
      private JedisPool jedisPool = wxy.getJedisPool();
      private Jedis jedis = null;

        try{

         jedis = jedisPool.getResource();
		 //
         jedis.exists();
         //
		 
		 }finally{
		 
		 if (null != jedis) {
            jedis.close();
        }
		 }
		 
    }

**Comment by sazzad16** [comment]
First of all, this back-n-forth proves why this post should've been in Discussions.

Coming to your code, my previous comment hits a bulls eye! You're keeping a reference of an object and risking of closing it twice (in multi-threaded environment).

Try to code in following way:

```java
public class xyz{
  private JedisPool jedisPool = wxy.getJedisPool();

    try (Jedis jedis = jedisPool.getResource()) {
      //
      jedis.exists();
      //
    }
}
```

It doesn't save a reference of a Jedis object and ensure closing the object exactly once.

**Comment by madhub05** [comment]
After implementing try with resource to Jedis Object like above, I am seeing below issue intermittently

Exception while executing function: Functions.getRelevantContent Result: Failure
Exception: JedisConnectionException: Attempting to read from a broken connection
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
	at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
	at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:331)
	at redis.clients.jedis.Connection.getOne(Connection.java:317)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:131)
	at redis.clients.jedis.Jedis.exists(Jedis.java:5020)
	at com.abnamro.pra.controllers.SdlConnector.getSdlResponse(SdlConnector.java:91)
	at com.abnamro.pra.controllers.RelevantContentController.getRelevantContent(RelevantContentController.java:90)
	at com.abnamro.pra.Conten

**Comment by sazzad16** [comment]
The connection is likely to be broken before the command is being executed.
A connection can be broken for way too many reasons. I.e.
- Network issue
- Very large amount of data is being fetched
- etc
