### ISSUE TITLE
subscribe  Unexpected end of stream

### ISSUE THREAD

**Issue by hello-piper** [redis/jedis#3501]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. redis:
  host: localhost
  port: 6379
  password: 123456
  timeout: 30000
  minIdle: 3
  maxIdle: 10
  maxActive: 100
  maxWait: 3000

2.            GenericObjectPoolConfig<Connection> poolConfig = new GenericObjectPoolConfig<>();
        poolConfig.setMinIdle(config.getMinIdle());
        poolConfig.setMaxIdle(config.getMaxIdle());
        poolConfig.setMaxTotal(config.getMaxActive());
        poolConfig.setMaxWait(Duration.ofMillis(config.getMaxWait()));
        if (StringUtil.isEmpty(config.getPassword())) {
            JEDIS_POOL = new JedisPooled(poolConfig, config.getHost(), config.getPort(), config.getTimeout());
        } else {
            JEDIS_POOL = new JedisPooled(poolConfig, config.getHost(), config.getPort(), config.getTimeout(), config.getPassword());
        }

3.JEDIS_POOL.subscribe(new JedisPubSub() {
            @Override
            public void onMessage(String channel, String message) {
                log.info("onMessage >>> {} {}", channel, message);
                handler(JSON.parseObject(message, Msg.class));
            }
        }, Constants.CHANNEL_IM_MESSAGE), "AbstractMsgConsumer Thread").start();

4.Exception in thread "AbstractMsgConsumer Thread" redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:46)
	at redis.clients.jedis.Protocol.process(Protocol.java:126)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:335)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:262)
	at redis.clients.jedis.Connection.auth(Connection.java:446)
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:380)
	at redis.clients.jedis.Connection.<init>(Connection.java:61)
	at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:68)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:29)
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:7)
	at redis.clients.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:63)
	at redis.clients.jedis.UnifiedJedis.subscribe(UnifiedJedis.java:3538)
	at io.piper.common.spi.AbstractMsgConsumer.lambda$new$1(AbstractMsgConsumer.java:55)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by sazzad16** [comment]
The connection is being closed from server side immediately after creating the socket. This is not `subscribe` specific issue, as it seems.
