### ISSUE TITLE
redis.clients:jedis:3.5.1升级到redis.clients:jedis:5.0.0

### ISSUE THREAD

**Issue by East-live** [redis/jedis#3530]
### Expected behavior

如何解决
报错：
redis/clients/jedis/Queable
java.lang.NoClassDefFoundError: redis/clients/jedis/Queable
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:463)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:393)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:373)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:237)
![image](https://github.com/redis/jedis/assets/115361792/c574e83f-0082-4d41-95d6-05a3381d2827)

### Actual behavior

Write here what happens instead ...
Jedis:5.0.0中Queable已经移除，但spring-data-redis:3.1.3还是使用了Queable，该怎么操作才能使用Jedis:5.0.0

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by sazzad16** [comment]
Jedis 5.0 is only supported from Spring 3.2.0.
