### ISSUE TITLE
Add support for automatic failover in Pipeline

### ISSUE THREAD

**Issue by uglide** [redis/jedis#3568]
### Expected behavior

The `Pipeline` class supports automatic failover.

### Actual behavior

The `Pipeline` class uses the `Connection` class directly instead of utilizing the Command executor with Circuit breaker support.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Follow the https://github.com/redis/jedis/blob/master/docs/failover.md instructions
2. Use `pipelined()` to send commands as a command
3. Simulate the Redis connection problem by shutting down the first cluster.

### Redis / Jedis Configuration
https://github.com/redis/jedis/blob/master/docs/failover.md

#### Jedis version:
5.0

#### Redis version:
Any

#### Java version:
Any

**Comment by banker** [comment]
In case it's useful, here's the pipeline stack trace on connection failure compared with the basic command stack strace (when failover is configured):

**Pipeline**
```
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
	at redis.clients.jedis.Connection.connect(Connection.java:195)
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:393)
	at redis.clients.jedis.Connection.<init>(Connection.java:68)
	at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:29)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider$Cluster.getConnection(MultiClusterPooledConnectionProvider.java:305)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider.getConnection(MultiClusterPooledConnectionProvider.java:249)
	at redis.clients.jedis.UnifiedJedis.pipelined(UnifiedJedis.java:4796)
	at org.example.Main.main(Main.java:34)
```

**Basic command**
```
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
	at redis.clients.jedis.Connection.connect(Connection.java:195)
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:393)
	at redis.clients.jedis.Connection.<init>(Connection.java:68)
	at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:29)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider$Cluster.getConnection(MultiClusterPooledConnectionProvider.java:305)
	at redis.clients.jedis.executors.CircuitBreakerCommandExecutor.handleExecuteCommand(CircuitBreakerCommandExecutor.java:59)
	at redis.clients.jedis.executors.CircuitBreakerCommandExecutor.lambda$executeCommand$0(CircuitBreakerCommandExecutor.java:45)
	at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$4(Retry.java:211)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$5(CircuitBreaker.java:194)
	at io.github.resilience4j.core.SupplierUtils.lambda$recover$5(SupplierUtils.java:119)
	at redis.clients.jedis.executors.CircuitBreakerCommandExecutor.executeC	ommand(CircuitBreakerCommandExecutor.java:52)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
	at redis.clients.jedis.UnifiedJedis.get(UnifiedJedis.java:722)
	at org.example.Main.main(Main.java:34)
```

**Comment by banker** [comment]
This issue also seems to apply to every method from `UnifiedJedis` that does not utilize the `executeCommand` code path. This includes:

- `pipelined()`
- `multi()`
- `subscribe()`
- methods that use `JedisCommandIterationBase`
