### ISSUE TITLE
Not able to successfully execute JedisCluster.ftCreate(...) method in Redis Cluster environment

### ISSUE THREAD

**Issue by YaraslauBarysenka** [redis/jedis#3592]
### Expected behavior
Index is created in Redis Cluster environment using JedisCluster.

### Actual behavior
JedisExeption occurs in during index creation  in Redis Cluster environment using JedisCluster.
Jedis sends FT.CREATE commands to all Cluster Nodes (3 Masters and 3 Replicas) instead of corresponds single Master Node (IndexName`s hash slot value should be related to this Master Node). As result 5 commands are failed results and 1 command is successed under Jedis hood.

### Steps to reproduce:
Try to create any Index using JedisCluster like this:
`        String IP = "127.0.0.1";
         Set<HostAndPort> nodes = Set.of(
                new HostAndPort(IP, 7000),
                new HostAndPort(IP, 7001),
                new HostAndPort(IP, 7002)
        );
        
        JedisCluster jedis = new JedisCluster(nodes);

        jedis.ftCreate("user-index",
                FTCreateParams.createParams()
                        .on(IndexDataType.JSON)
                        .addPrefix("user:"),
                TextField.of("$.name").as("name"),
                TagField.of("$.city").as("city"),
                NumericField.of("$.age").as("age")
        );`

### Redis / Jedis Configuration
Redis cluster: 3 Masters and 3 Replicas.

#### Jedis version:
5.0.1

#### Redis version:
6.2.7

#### Java version:
17

**Comment by C-o-s-m-o-S** [comment]
I have the same issue.

**Comment by sazzad16** [comment]
You're using RediSearch Light (assuming from the behavior). This is not the default.

Do
```java
JedisCluster.setBroadcastAndRoundRobinConfig(new JedisBroadcastAndRoundRobinConfig() {
    @Override public RediSearchMode getRediSearchModeInCluster() { return RediSearchMode.LIGHT; }
});
```

**Comment by YaraslauBarysenka** [comment]
Thanks @sazzad16 for the quick response.
This setting is not solve the issue.  In this case try to execute one commands but on random Redis Node and I got an exception:
`
redis.clients.jedis.exceptions.JedisClusterOperationException: Cluster retry deadline exceeded.
	at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:124)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
	at redis.clients.jedis.UnifiedJedis.checkAndBroadcastCommand(UnifiedJedis.java:260)
	at redis.clients.jedis.UnifiedJedis.ftDropIndex(UnifiedJedis.java:3656)
	at com.allot.common.data.redis.dao.test.TestRedis.main(TestRedis.java:204)

`

Jedis should calculate a proper slot based on IndexName value and execure FT.CREATE command on proper Master Node, not randomly.

I prepares a workaraund for  it like:

`
// instead of this call
jedisCluster.ftCreate(String indexName, IndexOptions indexOptions, Schema schema)

// I started to use this workaraund:

  private CommandObject<String> ftCreate(String indexName,
                                         IndexOptions indexOptions,
                                         Schema schema) {
                                         
       // 'key(indexName)' is used here instead of 'add(indexName)' as it done inside Jedis                               
      CommandArguments args = commandArguments(SearchProtocol.SearchCommand.CREATE).key(indexName)
              .addParams(indexOptions).add(SearchProtocol.SearchKeyword.SCHEMA);
      schema.fields.forEach(args::addParams);
      return new CommandObject<>(args, BuilderFactory.STRING);
  }

  private ClusterCommandArguments commandArguments(ProtocolCommand command) {
      return new ClusterCommandArguments(command);
  }


`
Jedis`s implementation of ftCreate method:
![image](https://github.com/redis/jedis/assets/5345908/012b0ede-6688-42da-a99c-4e288a401d94)

Jedis should calcuate slot value here, but actually slot value is -1 now:
![image](https://github.com/redis/jedis/assets/5345908/581e3b6e-ce93-4657-9d4e-ec40753dee2a)


@sazzad16 Please take a look.

**Comment by sazzad16** [comment]
@YaraslauBarysenka Could you please check with latest 5.1.0-snapshot?

**Comment by YaraslauBarysenka** [comment]
@sazzad16 Where I can retrive latest 5.1.0-snapshot?

**Comment by sazzad16** [comment]
@YaraslauBarysenka 
1. https://github.com/redis/jedis/blob/master/docs/jedis-maven.md 
2. Ask here https://github.com/RediSearch/RediSearch. There are also discord and Redis forum.

**Comment by YaraslauBarysenka** [comment]
Looks like it works only since Jedis 5.1.0-snapshot, but is required to set RediSearchMode.LIGHT, otherwise Jedis executes FT.CREATE commands on all Redis Cluster Nodes (all Masters and all Replicas) under the hood and from my point of view it is an issue as well.

@sazzad16 , do we have any cases/opportunitinies where we need (or Redis/RedisSearch allow to do it?) to create the same index on all Redis Cluster Nodes? I don't think so.

**Comment by sazzad16** [comment]
@YaraslauBarysenka The default behavior is defined by Redis management.

(Apologies for late reply.)

**Comment by sazzad16** [comment]
Resolved by #3593
