### ISSUE TITLE
Failed to establish connection to redis cluster mode deployment

### ISSUE THREAD

**Issue by ashok-mariyala** [redis/jedis#3613]
### Expected behavior

Jedis java client should connect with Redis cluster deployment.

### Actual behavior

Jedis java client failed to connect with Redis cluster deployment.

### Steps to reproduce:

1. Install redis cluster deployment in kubernetes cluster (`helm install redis oci://registry-1.docker.io/bitnamicharts/redis-cluster -n redis`)
2. Portforward 6379 to local (` kubectl port-forward svc/redis-redis-cluster 6379 -n redis`)
3. Execute Jedis java client

#### Redis version: 
Chart version: redis-cluster-9.1.3
App Version: 7.2.3

#### Java version:
```
java --version
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)
```
**Java Jedis code snippet**

```
    try {
	var redisHostName = "127.0.0.1"
	var redisPort = 6379;
	var redisUserName = "default";
	var redisPassword = "HhKh5HriPG";
			
	Set<HostAndPort> nodes = new HashSet<>();
        nodes.add(new HostAndPort(redisHostName, redisPort)); 
        cluster = new JedisCluster(nodes, redisUserName, redisPassword);
	        
        cluster.set("testkey", "testvalue");
	System.out.println(cluster.get("testkey"));

	} catch(Exception e) {
		e.printStackTrace();
	}
```
**Exception**
```
redis.clients.jedis.exceptions.JedisClusterOperationException: Cluster retry deadline exceeded.
	at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:125)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:183)
	at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:651)
	at com.ashok.redis.RedisClusterCacheClient.initRedisClusterConnection(RedisClusterCacheClient.java:43)
	at com.ashok.redis.RedisClusterCacheClient.<init>(RedisClusterCacheClient.java:28)
	at com.ashok.redis.RedisClusterCacheClient.getInstance(RedisClusterCacheClient.java:54)
	at com.ashok.redis.RedisClusterCacheClient.main(RedisClusterCacheClient.java:23)
```

**Comment by sazzad16** [comment]
@ashok-mariyala Can you connect and operate using other clients, e.g. redis-cli?

**Comment by ashok-mariyala** [comment]
@sazzad16 Thanks for your response. I am able to connect and insert data using redis-cli commands. Please find the following output.

```
ashok.mariyala@MacBook-Pro-110 ~ % kubectl exec -it redis-redis-cluster-0 -n redis -- /bin/bash
I have no name!@redis-redis-cluster-0:/$ redis-cli -c
127.0.0.1:6379> AUTH HhKh5HriPG
OK
127.0.0.1:6379> role
1) "master"
2) (integer) 3836
3) 1) 1) "10.42.0.208"
      2) "6379"
      3) "3836"
127.0.0.1:6379> SET name Ashok
-> Redirected to slot [5798] located at 10.42.0.210:6379
OK
10.42.0.210:6379> GET name
"Ashok"
10.42.0.210:6379> 
```

**Comment by sazzad16** [comment]
@ashok-mariyala What happens if you (try to) connect to `10.42.0.208:6379` and `10.42.0.210:6379` directly from Jedis?

**Comment by ashok-mariyala** [comment]
@sazzad16 I am getting the same error even though i am using `10.42.0.208:6379` and `10.42.0.210:6379` directly from Jedis?

**Comment by sazzad16** [comment]
@ashok-mariyala You can't get same error (JedisClusterOperationException) from Jedis class/object.

If it was not clear enough, I meant Jedis class/object just this earlier. So try `new Jedis("10.42.0.208", 6379)` and `new Jedis("10.42.0.210", 6379)`.

**Comment by ashok-mariyala** [comment]
@sazzad16 Okay sure. I am running redis in Kubernetes and here `10.42.0.208` and `10.42.0.210` addresses are changed to `10.42.0.10` and `10.42.0.252`
```
ubuntu@ashok:~$ kubectl exec -it redis-redis-cluster-0 -n redis -- /bin/bash
I have no name!@redis-redis-cluster-0:/$ redis-cli -c
127.0.0.1:6379> AUTH HhKh5HriPG
OK
127.0.0.1:6379> role
1) "master"
2) (integer) 6188
3) 1) 1) "10.42.0.10"
      2) "6379"
      3) "6188"
127.0.0.1:6379> SET name Ashok
-> Redirected to slot [5798] located at 10.42.0.252:6379
OK
10.42.0.252:6379> GET name
"Ashok"
10.42.0.252:6379>
```
Here is the result for connecting through jedis.
Using **10.42.0.10**
```
try {
	var redisHostName = "10.42.0.10";
	var redisPort = 6379;
	var redisUserName = "default";
	var redisPassword = "HhKh5HriPG";
	jedis = new JedisPooled(redisHostName, redisPort, redisUserName, redisPassword);
		
	jedis.set("Name", "Ashok Kumar");	
	System.out.println(jedis.get("Name"));
} catch(Exception e) {
	e.printStackTrace();
}
```
**Result**
```
redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 8680 10.42.0.252:6379
	at redis.clients.jedis.Protocol.processError(Protocol.java:79)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:335)
	at redis.clients.jedis.Connection.getOne(Connection.java:317)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:131)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:183)
	at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:651)
	at com.ashok.redis.RedisCacheClient.initRedisConnection(RedisCacheClient.java:60)
	at com.ashok.redis.RedisCacheClient.<init>(RedisCacheClient.java:45)
	at com.ashok.redis.RedisCacheClient.getInstance(RedisCacheClient.java:104)
	at com.ashok.redis.RedisCacheClient.main(RedisCacheClient.java:22)
redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 9411 10.42.0.252:6379
	at redis.clients.jedis.Protocol.processError(Protocol.java:79)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:335)
	at redis.clients.jedis.Connection.getOne(Connection.java:317)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:131)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:183)
	at redis.clients.jedis.UnifiedJedis.hget(UnifiedJedis.java:1335)
	at com.ashok.redis.RedisCacheClient.get(RedisCacheClient.java:117)
	at com.ashok.redis.RedisCacheClient.main(RedisCacheClient.java:22)
```
Using **10.42.0.252**
```
try {
	var redisHostName = "10.42.0.252";
	var redisPort = 6379;
	var redisUserName = "default";
	var redisPassword = "HhKh5HriPG";
	jedis = new JedisPooled(redisHostName, redisPort, redisUserName, redisPassword);
		
	jedis.set("Name", "Ashok Kumar");	
	System.out.println(jedis.get("Name"));
} catch(Exception e) {
	e.printStackTrace();
}
```
**Result**
Ashok Kumar

**Comment by sazzad16** [comment]
There seems not connection related issue. I can only think of increasing `maxTotalRetriesDuration` parameter.

**Comment by ashok-mariyala** [comment]
@sazzad16 I didn't find any constructor to increase `maxTotalRetriesDuration` parameter along with user name and password authentication.  How do i increase the `maxTotalRetriesDuration` parameter?

**Comment by ashok-mariyala** [comment]
@sazzad16 I tried to increase `maxTotalRetriesDuration` to `60` and `120` seconds. Still i am facing the same issue. Here is my code block.

```
try {
	var redisHostName = "127.0.0.1";
	var redisPort = 6379;
	var redisUserName = "default";
	var redisPassword = "HhKh5HriPG";
		
	Set<HostAndPort> nodes = new HashSet<>();
        nodes.add(new HostAndPort(redisHostName, redisPort));
	        
        DefaultJedisClientConfig config = DefaultJedisClientConfig.builder().user(redisUserName).password(redisPassword).build();
	 
        cluster = new JedisCluster(nodes, config, 5, Duration.ofSeconds(120));
	        
        cluster.set("Name", "Ashok Kumar");
        System.out.println(cluster.get("Name"));
} catch(Exception e) {
	e.printStackTrace();
}
```
**Result**
```
redis.clients.jedis.exceptions.JedisClusterOperationException: No more cluster attempts left.
	at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:129)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:183)
	at redis.clients.jedis.UnifiedJedis.set(UnifiedJedis.java:651)
	at com.ashok.redis.RedisClusterCacheClient.initRedisClusterConnection(RedisClusterCacheClient.java:50)
	at com.ashok.redis.RedisClusterCacheClient.<init>(RedisClusterCacheClient.java:33)
	at com.ashok.redis.RedisClusterCacheClient.getInstance(RedisClusterCacheClient.java:61)
	at com.ashok.redis.RedisClusterCacheClient.main(RedisClusterCacheClient.java:28)
	Suppressed: redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
		at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
		at redis.clients.jedis.Connection.connect(Connection.java:188)
		at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:374)
		at redis.clients.jedis.Connection.<init>(Connection.java:61)
		at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:68)
		at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
		at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
		at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:29)
		at redis.clients.jedis.providers.ClusterConnectionProvider.getConnectionFromSlot(ClusterConnectionProvider.java:139)
		at redis.clients.jedis.providers.ClusterConnectionProvider.getConnection(ClusterConnectionProvider.java:95)
		at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:91)
		... 6 more
		Suppressed: java.net.SocketTimeoutException: Connect timed out
			at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
			at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
			at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
			at java.base/java.net.Socket.connect(Socket.java:633)
			at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73)
			... 19 more

```

**Comment by sazzad16** [comment]
@ashok-mariyala Firstly, it's not the same issue.

Seeing only the last error, I would've assumed that it could be port enabling, firewall, or similar issue.
But from previous comment, it seems it's not such issue.

Now I'm out of ideas. Sorry, couldn't help you much this time.

**Comment by ashok-mariyala** [comment]
@sazzad16 Issue is not with the Kubernetes cluster/port enabling/firewall or similar issue. The same cluster is working fine with Jedis client for Redis sentinal and Redis standalone deployments. I am facing issue with only Jedis client for Redis cluster deployment. Could you please let us know who will help on this issue? 

Thanks in advance.

**Comment by codingSy** [comment]
> @sazzad16 Issue is not with the Kubernetes cluster/port enabling/firewall or similar issue. The same cluster is working fine with Jedis client for Redis sentinal and Redis standalone deployments. I am facing issue with only Jedis client for Redis cluster deployment. Could you please let us know who will help on this issue?
> 
> Thanks in advance.

I encountered the same error, version 4.4.3. There is no obvious exception in the monitoring data from the redis server, but the Jedis client will first execute "redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out", and the error "redis.clients.jedis.exceptions.JedisClusterOperationException: Cluster retryjpg attempts exceeded." will be sent after retrying several times. And I have this problem after trying from version 3.7 to version 4.4.3. I look forward to your reply. Thanks!
@ashok-mariyala

**Comment by vimal7225s** [comment]
Hi @ashok-mariyala  @codingSy  Have you fixed this issue? I am facing the same error

Error was: Cluster retry deadline exceeded.
org.mule.runtime.api.connection.ConnectionException: Cluster retry deadline exceeded.
Caused by: redis.clients.jedis.exceptions.JedisClusterOperationException: Cluster retry deadline exceeded.
at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:124) ~[jedis-5.1.1.jar:?]

Here is my code

	boolean isSSL = this.tlsContext != null;
	if (isSSL) {
		try {
			SSLContext sslContext = this.tlsContext.createSslContext();
			this.sslParameters = sslContext.getDefaultSSLParameters();
			this.sslParameters.setEndpointIdentificationAlgorithm(
					this.endpointIdentificationAlgorithm.name().toLowerCase().replace("disabled", ""));
			this.sslParameters.setCipherSuites(this.tlsContext.getEnabledCipherSuites());
			this.sslParameters.setProtocols(this.tlsContext.getEnabledProtocols());

			this.sslSocketFactory = sslContext.getSocketFactory();
		} catch (Exception e) {
			logger.error("Invalid TLSConfiguration Exception");
		}
	}

	JedisClientConfig clientConfig = DefaultJedisClientConfig.builder()
			.ssl(isSSL).sslSocketFactory(sslSocketFactory)
			.user("default")
			.password(connectionParams.getPassword())
			.connectionTimeoutMillis(connectionParams.getConnectionTimeout())
			.hostnameVerifier(null)
			.build();

	Set<HostAndPort> nodes = new HashSet<HostAndPort>();
    nodes.add(new HostAndPort(connectionParams.getHost(), connectionParams.getPort()));

    GenericObjectPoolConfig<Connection> poolConfig = new GenericObjectPoolConfig<Connection>();
    poolConfig.setMaxTotal(10000);
    poolConfig.setMaxIdle(500);
    
    JedisCluster jedisCluster = new JedisCluster(nodes, clientConfig, poolConfig);

**Comment by codingSy** [comment]
@vimal7225s No, I had no choice but to give up Jedis. After switching to Luttuce, there was no problem.

**Comment by AlecBruns** [comment]
Any updates on this? I'm getting similar issues with Jedis

**Comment by xiaomixin** [comment]
Does there any updates for this issue ?

**Comment by Krymonota** [comment]
I also couldn't get Jedis to work with the Redis Cluster I had set up with the `bitnami/redis-cluster` Helm chart. Connecting to a single node via `Jedis` worked fine, but connecting via `JedisCluster` always resulted in a timeout, no matter what I tried:

```
[proxy] redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
[proxy] 	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:262) ~[?:?]
[proxy] 	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:55) ~[?:?]
[proxy] 	at redis.clients.jedis.Protocol.process(Protocol.java:131) ~[?:?]
[proxy] 	at redis.clients.jedis.Protocol.read(Protocol.java:221) ~[?:?]
[proxy] 	at redis.clients.jedis.Connection.protocolRead(Connection.java:384) ~[?:?]
[proxy] 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:397) ~[?:?]
[proxy] 	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:306) ~[?:?]
[proxy] 	at [REDACTED]
[proxy] 	at [REDACTED]
[proxy] 	at [REDACTED]
[proxy] 	at [REDACTED]
[proxy] 	at [REDACTED]
[proxy] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
[proxy] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
[proxy] 	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[proxy] Caused by: java.net.SocketTimeoutException: Read timed out
[proxy] 	at java.base/sun.nio.ch.NioSocketImpl.timedRead(Unknown Source) ~[?:?]
[proxy] 	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source) ~[?:?]
[proxy] 	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source) ~[?:?]
[proxy] 	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source) ~[?:?]
[proxy] 	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source) ~[?:?]
[proxy] 	at java.base/java.io.InputStream.read(Unknown Source) ~[?:?]
[proxy] 	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:256) ~[?:?]
[proxy] 	... 14 more
```

So I also gave up and switched to Lettuce, which works perfectly in this configuration. I didn't have this problem with phpredis either. So something seems to be different or wrong with Jedis.

**Comment by ggivo** [comment]
@Krymonota 
What **JedisCluster**  does is use the `"CLUSTER SLOTS"` command to initialize the cluster topology. It will connect to provided seed nodes and then will rely on `"CLUSTER SLOTS" `to build an internal map with the cluster topology. Even if the seed node **IP:port** is accessible, IP:ports resolved with  `CLUSTER SLOTS` might be internal to Kubernetes and not accessible.

I don't have the Bitnami cluster at hand to test it out, but looking at their documentation with the default setup, the cluster is not exposed externally out of the box. This means that using port-forward to a particular node will allow connecting to this node in standalone mode. But for **JedisCluster** client, you need to make sure the `IP/ports` of the individual nodes (as returned by `CLUSTER SLOTS` command) are accessible from the location where **JedisCluster** client is used. 

As a troubleshooting step I can suggest connecting to the cluster using `redis-cli` and running the `"CLUSTER SLOTS"` command, then try to verify that returned **IP:port**'s are accessible by connecting to them using `*redis-cli`  before trying with **JedisCluster** client.

Could you also provide the Jedis version you are testing with?

**Comment by Krymonota** [comment]
@ggivo Thanks for answering and the clarification.

The IP addresses returned by `CLUSTER SLOTS` were reachable by the pods running Jedis. This was checked with `redis-cli` from the pods and a direct connection via `Jedis` (instead of `JedisCluster`) to these IP addresses (which worked fine with PubSub). I also verified with `CLUSTER INFO` that the cluster state was `ok` and with `CLUSTER NODES` that all nodes were connected.

I can provide you with the output of both commands for the 3-master node setup that I use for local development:

`CLUSTER SLOTS`:
```
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "192.168.194.113"
      2) (integer) 6379
      3) "1002c77c72fd4b27ce6bda80f9d1bd52435f381c"
      4) (empty array)
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "192.168.194.104"
      2) (integer) 6379
      3) "9b574da223f7d1add96712fb715c96f96e277681"
      4) (empty array)
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "192.168.194.112"
      2) (integer) 6379
      3) "3d57a3ced8fc02156175bafbd1eb8ff4a2ce36fe"
      4) (empty array)
```

`CLUSTER NODES`:
```
9b574da223f7d1add96712fb715c96f96e277681 192.168.194.104:6379@16379 master - 0 1740562987640 2 connected 5461-10922
1002c77c72fd4b27ce6bda80f9d1bd52435f381c 192.168.194.113:6379@16379 myself,master - 0 0 1 connected 0-5460
3d57a3ced8fc02156175bafbd1eb8ff4a2ce36fe 192.168.194.112:6379@16379 master - 0 1740562988654 3 connected 10923-16383
```

I ran my tests with Jedis 5.2.0 and 5.3.0-beta1. I installed the Redis cluster 7.4.2 in a Kubernetes cluster v1.30.7 running on OrbStack. So there were no external nodes or firewall policies - everything was running locally on my computer and by default all IP addresses of the cluster are reachable on the system. I also checked that no Kubernetes network policies were active, and of course I even went so far as to restart everything and create a clean cluster from scratch.

What I also noticed during my experiments was that executing `ping` on the `JedisCluster` resource returned `PONG`, but after that `JedisCluster#getClusterNodes` had 0 elements.

And as I mentioned that Lettuce is working fine for me - this is the output of `RedisClusterClient#getPartitions`:
```
[proxy] [09:58:45 INFO]: Connected to Redis: RedisClusterNodeSnapshot [uri=redis://192.168.194.104, nodeId='9b574da223f7d1add96712fb715c96f96e277681', connected=true, slaveOf='null', pingSentTimestamp=0, pongReceivedTimestamp=1740563923453, configEpoch=2, replOffset=0, flags=[MASTER], aliases=[], slot count=5462]
[proxy] [09:58:45 INFO]: Connected to Redis: RedisClusterNodeSnapshot [uri=redis://192.168.194.113, nodeId='1002c77c72fd4b27ce6bda80f9d1bd52435f381c', connected=true, slaveOf='null', pingSentTimestamp=0, pongReceivedTimestamp=1740563924461, configEpoch=1, replOffset=0, flags=[MASTER], aliases=[], slot count=5461]
[proxy] [09:58:45 INFO]: Connected to Redis: RedisClusterNodeSnapshot [uri=redis://192.168.194.112, nodeId='3d57a3ced8fc02156175bafbd1eb8ff4a2ce36fe', connected=true, slaveOf='null', pingSentTimestamp=0, pongReceivedTimestamp=0, configEpoch=3, replOffset=0, flags=[MYSELF, MASTER], aliases=[redis://***@redis-redis-cluster.database.svc.cluster.local], slot count=5461]
```

`redis-redis-cluster.database.svc.cluster.local` is the `ClusterIP` service that I provided to `Jedis`, `JedisCluster` and Lettuce's `RedisClusterClient`. I also tried providing the 192.168.x IP address, which didn't work with `JedisCluster` either.

[By the way, Lettuce uses `CLUSTER NODES` instead of `CLUSTER SLOTS` to discover the topology.](https://github.com/redis/lettuce/discussions/1639)

So I suspect that Jedis has a problem processing the `CLUSTER SLOTS` response, or is expecting some prerequisites that are not met by my setup, and is somehow silently failing? (Perhaps missing replicas that are, however, not necessary for the operation of a Redis cluster?)

**Comment by ggivo** [comment]
Hi @Krymonota 
I try to reproduce the issue in my env using the following steps using **minikube** on MAC,
but in my env, **JedisCluster** test app was able to connect successfully & run the test command when running inside pod in the same namespace and after verifying the access to ip/ports returned by `CLUSTER SLOTS`.

**Jedis version** : 5.2.0
**Chart**   : bitnami/redis-cluster  
**Chart version** : redis-cluster-11.4.3	
**Redis verions** : 7.4.2

<details>
  <summary>Redis cluster in Kubernetes setup </summary>

``` bash
kubectl create namespace redis
helm install redis --set "password=changeme" bitnami/redis-cluster -n redis

export REDIS_PASSWORD=$(kubectl get secret --namespace "redis" redis-redis-cluster -o jsonpath="{.data.redis-password}" | base64 -d)

# Since I am running Docker on Mac I deployed the JedisCluster test app in Kubernetes namespace (redis)

# deploy some java-enabled image
kubectl run --namespace redis java-client --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image openjdk:17.0.2-jdk --command -- sleep infinity

#Upload test app creating JedisCluster 
kubectl cp ./target/JedisPlayground-1.0-SNAPSHOT.jar redis/java-client:/tmp/JedisPlayground-1.0-SNAPSHOT.jar -n redis
```

</details>
<details>
  <summary>Run JedisCluster test app from pod in kubernetes</summary>

```
kubectl exec --namespace redis -it java-client -- bash
bash-4.4# java -jar ./tmp/JedisPlayground-1.0-SNAPSHOT.jar redis-redis-cluster  6379 default changeme
testvalue
bash-4.4# java -jar ./tmp/JedisPlayground-1.0-SNAPSHOT.jar 10.244.0.42  6379 default changeme
testvalue
bash-4.4# java -jar ./tmp/JedisPlayground-1.0-SNAPSHOT.jar 10.244.0.47  6379 default changeme
testvalue
bash-4.4# java -jar ./tmp/JedisPlayground-1.0-SNAPSHOT.jar 10.244.0.43  6379 default changeme
testvalue
```

</details>
<details>
  <summary>Redis cluster info</summary>

```
kubectl -n redis get services
NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
redis-redis-cluster            ClusterIP   10.109.101.251   <none>        6379/TCP             12m
redis-redis-cluster-headless   ClusterIP   None             <none>        6379/TCP,16379/TCP   12m


kubectl exec --namespace redis -it redis-redis-cluster-0 -- bash
I have no name!@redis-redis-cluster-0:/$ redis-cli -h redis-redis-cluster
redis-redis-cluster:6379> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.0.42"
      2) (integer) 6379
      3) "5fc416f5eca9f9a0300ccf1104936796750da661"
      4) (empty array)
   4) 1) "10.244.0.47"
      2) (integer) 6379
      3) "ac91c017c9a08241995a7f939735a6a38ee94bbd"
      4) (empty array)
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.244.0.43"
      2) (integer) 6379
      3) "715b7824626affe04db5d79a569515c8c15f79fb"
      4) (empty array)
   4) 1) "10.244.0.45"
      2) (integer) 6379
      3) "ad14d2e97155c01a2c39be8bae54ba4a090a7bf5"
      4) (empty array)
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.244.0.46"
      2) (integer) 6379
      3) "91c012e2f4d8d2f4f286ee200d2d934f1ec84237"
      4) (empty array)
   4) 1) "10.244.0.44"
      2) (integer) 6379
      3) "0ffd6182a5611e5453b5090543b1cfac909dc475"
      4) (empty array)
```
</details>
<details>
  <summary>JedisCluster test app example</summary>

```java
package org.example;

import redis.clients.jedis.DefaultJedisClientConfig;
import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.JedisCluster;

import java.util.HashSet;
import java.util.Set;

class Main {
    public static void main(String[] args) {
        try {
            String redisHostName = args[0];
            int redisPort = Integer.parseInt(args[1]);
            String redisUserName = args[2];
            String redisPassword = args[3];

            Set<HostAndPort> nodes = new HashSet<>();
            nodes.add(new HostAndPort(redisHostName, redisPort));
            DefaultJedisClientConfig clientConfig = DefaultJedisClientConfig.builder()
                    .user(redisUserName)
                    .password(redisPassword)
                    .build();

            try (JedisCluster jedisCluster = new JedisCluster(nodes, clientConfig)) {
                jedisCluster.set("testkey", "testvalue");
                System.out.println(jedisCluster.get("testkey"));
            }

        } catch(Exception e) {
            e.printStackTrace();
        }
    }

}
```

</details>

> (Perhaps missing replicas that are, however, not necessary for the operation of a Redis cluster? - Apart from the risks, but that doesn't really matter for local development.)

Not sure this is related.

> redis-redis-cluster.database.svc.cluster.local is the ClusterIP service that I provided to Jedis, JedisCluster and Lettuce's RedisClusterClient. I also tried providing the 192.168.x IP address, which didn't work with JedisCluster either.

If JedisCluster is not able to connect via IP's, this looks like the primary suspect. As mentioned before, once connected, JedisCluster will perform direct connections to nodes using IP's resolved with CLUSTER SLOTS. This will happen at the first command execution. I believe a big part of the confusion comes from hiding/eating the root cause for **"Cluster retry deadline exceeded."** error.
Let me put PR, which will show the root cause.

**Comment by Krymonota** [comment]
@ggivo First of all, thanks for taking the time trying to reproduce it - I really appreciate it!

I followed your steps in a clean cluster, and what can I say - it works flawlessly regardless of whether I apply the default Helm chart values from `bitnami/redis-cluster` or my custom values with the master-only cluster! I even went so far as to try it out in the application running in my regular Kubernetes cluster that had these issues and can confirm that this works as well. I can't explain why at the moment. I'm quite confused as to why everything except `JedisCluster` worked and looked fine for me, unless it's somehow related to my original implementation which I haven't rebuilt yet. I think I'll just go as far as replacing Lettuce with Jedis again and then see if everything works smoothly :-)

**Comment by ggivo** [comment]
@ashok-mariyala 

Is this issue still relevant? 
I try to reproduce it using the steps described  with comment https://github.com/redis/jedis/issues/3613#issuecomment-2685990327  but it worked for me.
