### ISSUE TITLE
SocketTimeoutException:null

### ISSUE THREAD

**Issue by willvvvv1** [redis/jedis#3623]
### Expected behavior

Successfully obtained the connection

### Actual behavior

**The stack is as follows**
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:271)
	... 37 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host xxxxxxx
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:101)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1844)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 40 common frames omitted
Caused by: java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 47 common frames omitted

**The STW logs at relevant time points are as follows:**
2023-11-25T18:01:08.006+0800: 159912.478: [GC pause (G1 Evacuation Pause) (young)2023-11-25T18:01:08.050+0800: 159912.522: [SoftReference, 0 refs, 0.0000419 secs]2023-11-25T18:01:08.050+0800: 159912.522: [WeakReference, 19 refs, 0.0000094 secs]2023-11-25T18:01:08.050+0800: 159912.522: [FinalReference, 1732 refs, 0.0022983 secs]2023-11-25T18:01:08.052+0800: 159912.524: [PhantomReference, 20 refs, 109 refs, 0.0000713 secs]2023-11-25T18:01:08.052+0800: 159912.524: [JNI Weak Reference, 0.0000670 secs], 0.0488306 secs]
   [Parallel Time: 39.6 ms, GC Workers: 9]
      [GC Worker Start (ms): Min: 159912481.7, Avg: 159912481.8, Max: 159912481.8, Diff: 0.1]
      [Ext Root Scanning (ms): Min: 5.3, Avg: 6.4, Max: 12.2, Diff: 6.9, Sum: 57.9]
      [Update RS (ms): Min: 4.4, Avg: 10.1, Max: 11.2, Diff: 6.8, Sum: 90.9]
         [Processed Buffers: Min: 197, Avg: 322.1, Max: 388, Diff: 191, Sum: 2899]
      [Scan RS (ms): Min: 0.0, Avg: 0.1, Max: 0.1, Diff: 0.1, Sum: 0.6]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [Object Copy (ms): Min: 22.4, Avg: 22.7, Max: 22.8, Diff: 0.5, Sum: 204.5]
      [Termination (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
         [Termination Attempts: Min: 1, Avg: 1.2, Max: 3, Diff: 2, Sum: 11]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.4]
      [GC Worker Total (ms): Min: 39.3, Avg: 39.4, Max: 39.5, Diff: 0.2, Sum: 354.4]
      [GC Worker End (ms): Min: 159912521.2, Avg: 159912521.2, Max: 159912521.2, Diff: 0.1]
   [Code Root Fixup: 0.2 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.5 ms]
   [Other: 8.6 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 2.7 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.1 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.4 ms]
   [Eden: 7520.0M(7520.0M)->0.0B(7520.0M) Survivors: 160.0M->160.0M Heap: 10567.7M(19200.0M)->3052.3M(19200.0M)]
Heap after GC invocations=3735 (full 0):
 garbage-first heap   total 19660800K, used 3125506K [0x0000000310000000, 0x0000000311002580, 0x00000007c0000000)
  region size 16384K, 10 young (163840K), 10 survivors (163840K)
 Metaspace       used 246466K, capacity 258917K, committed 265664K, reserved 1284096K
  class space    used 28423K, capacity 30419K, committed 31704K, reserved 1048576K
}
 [Times: user=0.36 sys=0.00, real=0.05 secs] 
2023-11-25T18:01:08.057+0800: 159912.529: Total time for which application threads were stopped: 0.0730045 seconds, Stopping threads took: 0.0004622 seconds

### Redis / Jedis Configuration
use Spring Data Redis
spring.redis.jedis.pool.max-active=300
spring.redis.jedis.pool.max-idle=200
spring.redis.jedis.pool.min-idle=140
spring.redis.jedis.pool.max-wait=2s
spring.redis.jedis.pool.time-between-eviction-runs=6m

#### Jedis version:
2.9.3

#### Java version:
openjdk version "1.8.0_242"

I tried debugging and looked at the code. I initially guessed that STW occurred before TCP initiated the connection, causing the problem. However, this possibility was ruled out through STW log analysis. Now I am at a loss. Could you please help?

**Comment by sazzad16** [comment]
Jedis 2.9.x is quite old. We can only suggest you to check more latest releases. Some of these releases contain DNS related improvements which might help in your case. Thanks
