### ISSUE TITLE
Idle connections cause JedisException on eviction process

### ISSUE THREAD

**Issue by v-barros** [redis/jedis#3645]
### Expected behavior
Jedis client is working as expected, except for the destroy() method. Which throws a JedisException when there's an idle connection.
I think the eviction process should not broke in this scenario, once there's no guarantee that the application is using all the available connections when calling JedisPool.destroy();

### Actual behavior

When the application stops running and I call pool.destroy(), I found this exception:
```
2023-12-08 09:39:27,529 WARN r.c.j.JedisFactory: Error while close
redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
	at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:116) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.util.Pool.returnBrokenResource(Pool.java:98) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:382) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:15) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.Jedis.close(Jedis.java:3957) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:166) ~[jedis-3.6.3.jar:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:127) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:611) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:461) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:495) ~[commons-pool2-2.11.1.jar:2.11.1]
	at redis.clients.jedis.util.Pool.closeInternalPool(Pool.java:122) ~[jedis-3.6.3.jar:?]
	at redis.clients.jedis.util.Pool.destroy(Pool.java:109) ~[jedis-3.6.3.jar:?]
	at kg.apc.jmeter.config.redis.RedisDataSet.testEnded(RedisDataSet.java:270) ~[jmeter-plugins-redis-0.6.jar:?]
	at kg.apc.jmeter.config.redis.RedisDataSet.testEnded(RedisDataSet.java:255) ~[jmeter-plugins-redis-0.6.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:507) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:936) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:914) ~[commons-pool2-2.11.1.jar:2.11.1]
	at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:114) ~[jedis-3.6.3.jar:?]
	... 16 more
```

### Steps to reproduce:

What I did to try to understand this behavior was to log the number of idle connections right before calling the detroy() method, and what I found is that the number of idle connections is equal to the total of exceptions, so I guess the exception occurs only for these idle connections.

````
log.debug("getNumIdle:"+(pool.getNumIdle()));
pool.destroy();
````

Then, I modified the exit method in my application to retrieve all the connections before calling pool.destroy() and then I got no exceptions.
Here's the code:
````
 public void testEnded(String host) {
        log.debug("TestEnded()");
        int idleConn = pool.getNumIdle();
        for(int i=0;i<idleConn;i++){
           pool.getResource();
        }
        log.debug("getNumIdle:"+(pool.getNumIdle()));
        pool.destroy();
    }

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration


#### Jedis version: 3.6.3

#### Redis version: 7.2.3

#### Java version: openjdk 17.0.9

**Comment by sazzad16** [comment]
@v-barros Please clarify if it is `throws a JedisException` or just `logs a JedisException`? I hope you understand that there is a difference.
JedisPool.destroy() throws exception only with `Could not destroy the pool` message.

However, something is not right with your code flow. In case of idle connections, Jedis.close() should go to Client.close() and then Connection.close(). This is not happening in your case. Try updated version of commons-pool2 (also Jedis).

**Comment by sazzad16** [comment]
Closed due to inactivity.
