### ISSUE TITLE
Jedis connect failed when using dns resolver in jedis 5.1.2

### ISSUE THREAD

**Issue by ellabider** [redis/jedis#3871]
### Expected behavior

connect success

### Actual behavior

Write here what happens instead ...
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.connect(Connection.java:194) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.<init>(Connection.java:67) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Jedis.<init>(Jedis.java:220) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:170) ~[jedis-5.1.2.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[commons-pool2-2.12.0.jar:2.12.0]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378) ~[jedis-5.1.2.jar:?]
	
### Steps to reproduce:
try(Jedis jedis = new Jedis("redis-host.mv.com", 6379)) {
	System.out.println(jedis.ping()); // failed
}

most of time works as expected, but sometime randomly fails with a set of above failure with different redis endpoints

### Redis / Jedis Configuration
using AWS EC2 resolver

**Comment by sazzad16** [comment]
@ellabider @katsanva Was it fine with an earlier (but somewhat recent) version of Jedis?
What was the last Jedis version that works for you?

**Comment by ngavrailov** [comment]
Same issue on our side. I tried with 5.1.3, then with 5.0.0 and still have it. Upgrade was from 4.3.2.

**Comment by ellabider** [comment]
It occurred in 4.2.3 for sure. 3.8.0 - was OK, I think
