### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.

### ISSUE THREAD

**Issue by nagesh-sys** [redis/jedis#3877]
### Expected behavior

Failed to perform put and get operations into Redis 

Here is the stack trance 
```
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.connect(Connection.java:194) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.Connection.<init>(Connection.java:67) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[jedis-5.1.2.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[commons-pool2-2.12.0.jar:2.12.0]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:252) ~[jedis-5.1.2.jar:?]
	at redis.clients.jedis.UnifiedJedis.get(UnifiedJedis.java:730) ~[jedis-5.1.2.jar:?]
```
I configured the JedisPool like below

```
var redisHostName = System.getenv("REDIS_HOST");
		var redisPort = null !=  System.getenv("REDIS_PORT") ? Integer.parseInt(System.getenv("REDIS_PORT")) : 6379;
		var redisUserName = System.getenv("REDIS_USERNAME");
		var redisPassword = System.getenv("REDIS_PASSWORD");

		GenericObjectPoolConfig<Jedis> poolConfig = new GenericObjectPoolConfig<>();
		poolConfig.setMaxTotal(2000); // Set maximum number of connections
		poolConfig.setMaxIdle(300);  // Set maximum number of idle connections
		poolConfig.setMinIdle(100);   // Set minimum number of idle connections
		int timeout = 60000;
			        
		 JedisPool jedispool= new JedisPool(poolConfig, redisHostName, redisPort, timeout, redisUserName, redisPassword);

```

#### Java version: java 11 

org.apache.commons  : commons-pool2 2.12.0

**Comment by riham888** [comment]
we have the same issue:
<img width="389" alt="image" src="https://github.com/user-attachments/assets/e1b949ca-90ce-42b7-892f-1736e1c53dd6">

down in the trace, caused by socket timeout:
<img width="390" alt="image" src="https://github.com/user-attachments/assets/4897c3c5-3804-4a7d-8221-f0ce1b05ca7f">

so it resolves an IP address and then tries to open a socket and then it fails with timeout...
running in Azure,
it is jedis 5.1.1.

perhaps some kind of retry mechanism to be used?

**Comment by taylorbasso** [comment]
+1 same random error and stack trace. Will work fine for days and randomly get the error.

Interestingly, also using Azure Cache for Redis.

Jedis 4.3.2

**Comment by ggivo** [comment]
@taylorbasso @nagesh-sys

Based on the stack trace, a connect timed out error typically means the client couldn’t reach the Redis host — often due to DNS issues or network unavailability.

The exception message _"Failed to connect to any host resolved for DNS name"_  was  improved to include the contacted HostAndPort and detailed errors from each connection attempt (as suppressed exceptions). This should help clarify whether DNS resolution worked and why individual connections failed.

If needed, retry logic can be handled at the application level, or you can use [RetryableCommandExecutor](https://github.com/redis/jedis/blob/93928bb3701ba15297ce0449466aa214ebc9d8a5/src/main/java/redis/clients/jedis/executors/RetryableCommandExecutor.java#L24-L24).

Without reliable steps to reproduce, I don’t think this issue is actionable at the moment.
