### ISSUE TITLE
Java 21 and Virtual Threads: Timeout waiting for idle object

### ISSUE THREAD

**Issue by qyyxl** [redis/jedis#3905]
### Actual behavior

The following error occurs when I change the application's business thread to a virtual thread and the traffic suddenly increases：
```
	Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:461)
		at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:375)
		at redis.clients.util.Pool.getResource(Pool.java:49)
		at credis.java.client.pool.impl.CRedisJedisPool.getResource(CRedisJedisPool.java:103)
```

**Comment by sazzad16** [comment]
@qyyxl 

First of all, please mention relevant versions.

Jedis does not have any official release supporting virtual threads. But it expected from 5.2.0. In the mean time, the support is available in latest 5.2.0-SNAPSHOTs.

**Comment by sazzad16** [comment]
Could be related to #3927

**Comment by BinaryIgor** [comment]
@sazzad16 is it fixed already in the _5.2.0-SNAPSHOT_ version? At our company, we want to ditch Redisson in favor of Jedis simplicity and this bug is the only thing preventing us from doing it, because we do use Java 21 with Virtual Threads quite extensively.

**Comment by MaciejLipinski** [comment]
I second @BinaryIgor 's question about the fix in the 5.2.0 snapshot – it did not seem to be fixed in our tests with the `5.2.0-beta5` version.

**Comment by sazzad16** [comment]
@BinaryIgor @MaciejLipinski We did our part AFAIK. If you find something within Jedis code base, please let us know.

But one of our dependencies, commons-pool, is [yet to update](https://github.com/apache/commons-pool/pull/339).
