### ISSUE TITLE
ERR Syntax on jedis.setGet("My Key", "My Value", SetParams.setParams()); with redis 6.0.0

### ISSUE THREAD

**Issue by Tudor414** [redis/jedis#3953]
### Expected behavior

It should perform the setGet as in redis 6.2.14 or 7.2.0

### Actual behavior

```
Throws
redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
	at redis.clients.jedis.Protocol.processError(Protocol.java:109)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:228)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:350)
	at redis.clients.jedis.Connection.getOne(Connection.java:332)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:137)
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:252)
	at redis.clients.jedis.UnifiedJedis.setGet(UnifiedJedis.java:740)
	at com.dxc.utils.RedisLockerIT.setGetTest(RedisLockerIT.java:30)
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

```
@Test
	void setGetTest() {
		JedisPooled jedis = new JedisPooled("localhost", 6379);
		jedis.setGet("My Key", "My Value", SetParams.setParams());
	}
```

### Redis / Jedis Configuration

default

#### Jedis version:

5.1.5, present since at least 4.3.1

#### Redis version:
6.0.0
Does not reproduce with 6.2.14 or 7.2.0

#### Java version:
Java 17

**Comment by sazzad16** [comment]
The feature is not supported by concerned Redis versions. Jedis has nothing to do with it.
Check the [command doc](https://redis.io/commands/set).
![image](https://github.com/user-attachments/assets/49903a06-ef0b-4242-984d-34ef680abbf2)
