### ISSUE TITLE
jedis pool WAITING

### ISSUE THREAD

**Issue by flylee85** [redis/jedis#4005]
### Expected behavior

jedis pool no WAITING

### Actual behavior

"http-nio-8085-exec-2" #47 daemon prio=5 os_prio=0 tid=0x00007f594dc49800 nid=0x73c0 waiting on condition [0x00007f586eff4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000082c02c40> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:587)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:440)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
	at org.springframework.data.redis.core.RedisConnectionUtils.bindConnection(RedisConnectionUtils.java:67)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:192)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:43)

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=15
spring.redis.password=abc
spring.redis.jedis.pool.max-active=50
spring.redis.jedis.pool.max-wait=1000
spring.redis.jedis.pool.max-idle=20
spring.redis.jedis.pool.min-idle=2
spring.redis.timeout=5000
#### Jedis version:
2.10.2
#### Redis version:
3.2.9
#### Java version:
jdk8

**Comment by ggivo** [comment]
As commented by @sazzad16 it is an old release. Please retest with the latest one, and if the issue persists, to be actionable provide also steps to reproduce it.
