### ISSUE TITLE
JMX error when running Jedis on JBoss 5.2. 

### ISSUE THREAD

**Issue by pkgoncalves** [redis/jedis#926]
The following exception is thrown when Jedis 2.6.2 on JBoss 5.2:

```
javax.management.NotCompliantMBeanException: Cannot obtain mxbean interface for: class org.apache.commons.pool2.impl.GenericObjectPool
```

The full stack trace is:

``` java
javax.management.NotCompliantMBeanException: Cannot obtain mxbean interface for: class org.apache.commons.pool2.impl.GenericObjectPool
    at org.jboss.mx.mxbean.MXBeanMetaData.<init>(MXBeanMetaData.java:174)
    at org.jboss.mx.mxbean.MXBeanDelegate.buildMBeanInfo(MXBeanDelegate.java:456)
    at org.jboss.mx.mxbean.MXBeanDelegate.getMBeanInfo(MXBeanDelegate.java:334)
    at org.jboss.mx.server.RawDynamicInvoker.getMBeanInfo(RawDynamicInvoker.java:187)
    at org.jboss.mx.server.RawDynamicInvoker.preRegister(RawDynamicInvoker.java:205)
    at org.jboss.mx.server.registry.BasicMBeanRegistry.invokePreRegister(BasicMBeanRegistry.java:700)
    at org.jboss.mx.server.registry.BasicMBeanRegistry.registerMBean(BasicMBeanRegistry.java:227)
    at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
    at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
    at org.jboss.mx.interceptor.AbstractInterceptor.invoke(AbstractInterceptor.java:138)
    at org.jboss.mx.server.Invocation.invoke(Invocation.java:90)
    at org.jboss.mx.interceptor.ModelMBeanOperationInterceptor.invoke(ModelMBeanOperationInterceptor.java:140)
    at org.jboss.mx.server.Invocation.invoke(Invocation.java:90)
    at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
    at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
    at org.jboss.mx.server.MBeanServerImpl$3.run(MBeanServerImpl.java:1431)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.jboss.mx.server.MBeanServerImpl.registerMBean(MBeanServerImpl.java:1426)
    at org.jboss.mx.server.MBeanServerImpl.registerMBean(MBeanServerImpl.java:376)
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:947)
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:132)
    at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107)
    at redis.clients.util.Pool.initPool(Pool.java:43)
    at redis.clients.util.Pool.<init>(Pool.java:31)
    at redis.clients.jedis.JedisPool.<init>(JedisPool.java:73)
    at redis.clients.jedis.JedisPool.<init>(JedisPool.java:15)
```

I've tried to upgrade commons-pool2 to the latest version but had no success.

**Comment by marcosnils** [comment]
@pkgoncalves are you still having this issue?. I'm wondering if there's a way I could easily try this without installing the complete jboss stack in my pc. Are you using EAP or wildfly?

**Comment by pkgoncalves** [comment]
Hi @marcosnils! Yes, the issue is still present. I'm using the EAP version of JBoss 5.2. After the exception is thrown, I can still get connections from the Jedis pool, but I don't know if I'm getting a pooled connection or just a standalone one.

**Comment by marcosnils** [comment]
@pkgoncalves. Is there a VM por docker imagen I can use to reproduce this?

**Comment by poroto20** [comment]
I have the same problem. Have you found any fix?

**Comment by marcosnils** [comment]
@liriarte @pkgoncalves is there an easy way to try this without installing the complete EAP suite in my pc?. Is there a docker container or a VM I can use to test?

**Comment by liriarte** [comment]
Probably the easiest way is to install it in a blank CentOS. I can share the rpm

**Comment by marcosnils** [comment]
@liriarte lol, I see it very unlikely to install another OS to try this. Doesn't Oracle provide a VirtualMachine with EAP installed or somethinf?

**Comment by liriarte** [comment]
No, they don't. You could 'docker pull centos' to get the OS. I am trying to find another way...

**Comment by marcosnils** [comment]
@liriarte ok, I'll try to setup the environment some time this week to test this.

**Comment by liriarte** [comment]
@marcosnils you can use this image: https://registry.hub.docker.com/u/tutum/jboss/
JBoss EAP 5.2 runs JBoss AS 5.2.0.GA, so you can use tutum/jboss:as5

**Comment by marcosnils** [comment]
amazing @liriarte I'll give it a try and provide some feedback hopefully later today

**Comment by marcosnils** [comment]
@liriarte I've just deployed [THIS](https://github.com/marcosnils/jedis-tomcat-issue) example application into the container you've provided and It ran without throwing any errors problems. Is there something I should configure in Jboss to get the errors you're seeing?

**Comment by liriarte** [comment]
Is version 2.7.0 available in the public repos? I was trying 2.6.2 and it does not have the constructor JedisPool jp = new JedisPool();
I was using new JedisPool(new JedisPoolConfig(), "localhost")
Do you think that this be the problem?

**Comment by marcosnils** [comment]
@liriarte yes, 2.7.0 is available in the public repos. However, I don't think that upgrading the version will solve the issue. Can you try running your app (or at least some small portion of it) in the container you provided to see if the issue is present there also?

**Comment by liriarte** [comment]
@marcosnils I am afraid it would be that easy. Let me see if I can find a way to help you reproducing the problem. Thanks!

**Comment by marcosnils** [comment]
@liriarte another thing you can do is deploy the WAR of the project i've posted before and check if that raises the same exception as you're getting with your app. I guess that should be quite easy right?

**Comment by liriarte** [comment]
@marcosnils I tried it and I got the same error. It may be a problem with EAP and not AS

**Comment by marcosnils** [comment]
@liriarte seems like. We need to find a docker image or a VM with EAP so I can debug..

**Comment by liriarte** [comment]
@marcosnils I think you can this this image https://registry.hub.docker.com/u/enschede/jboss-eap-5.2.0/

**Comment by marcosnils** [comment]
ok, I'll give it a try with that image!.

**Comment by marcosnils** [comment]
@liriarte I could reproduce the error that you're getting when deploying the WAR application. However, even though I'm getting the same stacktrace as you, my application still runs without a problem. 

Are you seeing errors when your application is running in production or only when you deploy it?

**Comment by liriarte** [comment]
@marcosnils once I get the error, then JBoss gets unstable, and I need to restart it. Sometimes I can even set/get to Redis, but then I need to restart it.

**Comment by marcosnils** [comment]
Ok, I'll investigate it during the weekend and see if we can find a way to
make it work with EAP 5.2

**Comment by liriarte** [comment]
@marcosnils thanks! I posted on JBoss forum as well

**Comment by marcosnils** [comment]
@liriarte I'd also open a ticket in the apache commons-pool issue tracker https://commons.apache.org/proper/commons-pool/issue-tracking.html as the exception is being generated from commons-pool

**Comment by nemo97** [comment]
Seems like JMX spec is different JBOSS EAP 5.2, I patched "common-pool2" to make it work eap 5.2

**Comment by amitkapps** [comment]
@nemo97 would you mind sharing your fix for this?

**Comment by jianzli** [comment]
@nemo97  would you mind sharing your fix for this?

**Comment by pkgoncalves** [comment]
Hi guys! I know this is an old issue, but I had to do a little maintenance on the legacy system that I got the error a couple of years ago and even after upgrading Jedis to version 3.3.0 the error still happens on JBoss EAP 5.2 but I was able to avoid it setting the property **jxmEnabled** to **false** on **JedisPoolConfig**.

`JedisPoolConfig config = JedisPoolConfig();
config.setJmxEnabled(false);`

Don't know if disabling JMX is a viable workaround to everyone using JBoss EAP 5.2. But it's quite an old server version, maybe it's not worth anymore supporting it. :information_desk_person:

**Comment by sazzad16** [comment]
https://github.com/redis/jedis/issues/926#issuecomment-693792243

> I was able to avoid it setting the property **jxmEnabled** to **false** on **JedisPoolConfig**.
> 
> `JedisPoolConfig config = JedisPoolConfig(); config.setJmxEnabled(false);`

**Comment by jianzli** [comment]
同志，邮件已收到，您辛苦了，改天聚聚……
